### ISSUE TITLE
Screen real estate / placement of logos and banners

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#100]
Real estate/placement of logos and banners need to be consistent.  

1) Getting started - logo and text is too close to the edge of the screen. Statistics Canada banner is too high, it's being blocked by my carrier/time/battery banner (iphone) 

2) Terms and conditions - logo and text is too close to the edge of the screen. Statistics Canada banner is missing and needs to be added. 

3) Secure your account - logo is too close to top of screen.

**Comment by AJBouzidi** [comment]
this has been fixed
