### ISSUE TITLE
Secure your account - password does not match 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#101]
"Password's does not match" is incorrect.t  Please refer to content file for proper wording.

**Comment by armonkolaei** [comment]
@AJBouzidi i need text for these keys on registration page
for password confirm error text:
            "reg.pass_conf.empty": "Password cannot be empty",
            "reg.pass_conf.match": "Password's do not match",

**Comment by mullhol** [comment]
@armonkolaei 
Password cannot be empty / Le mot de passe ne peut pas être vide 

Instead of password do not match, you can use: 
Password is incorrect / Mauvaise mot de passe 

cc: @AJBouzidi

**Comment by armonkolaei** [comment]
@AJBouzidi this has been done
