### ISSUE TITLE
Fix the password help screen 

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#103]
1. This screen should be deplayed upon the user navigate to this screen. 
2. text need revision: "at least 8 characters."
3. Asset for check box and the same theme as other. 

![Password Requirements](https://user-images.githubusercontent.com/58231743/75254665-aefd8e00-57ae-11ea-883e-d0c0f314c7b3.PNG)

**Comment by armonkolaei** [comment]
As discussed the dialog has been updated.
1. delayed entry??? not sure what you mean. but on entry we now show the dialog by default first time.
2. I sent the text on slack but received back the password validation text. These texts should be different.
as agreed it will be:
8 caractères
une majuscule
un caractère spécial
une minuscule
un chiffre
3. layout and theme also updated.
