### ISSUE TITLE
CMP: Test User agent coming from Apple device in CMP 

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#104]

**Comment by thierryrama** [comment]
Looking at the database, here is a sample of User-Agent and what is being detected by EQ/CMP:

Captured User-Agent|Detected Web Browser|Detected Device Type|Comments
---------------------|-----------------------|----------------------|-----------
0198033c-2294-4f33-ae71-df450b115821|Other|Other|Not good
6rgvLHVAE6FUmrngauZP|Other|Other|Not good. The length as deviceId is good but the user-agent is not good
Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.190920.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36|Chrome Mobile WebView 74.0|Generic Smartphone|Not good. The user-agent is good but missing the deviceId
Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.87 Mobile Safari/537.36|Chrome Mobile WebView 80.0|OnePlus ONEPLUS A5000|Not good. The user-agent is good but missing the deviceId
ozilla/5.0 (Linux; Android 9; SAMSUNG SM-J337W Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.0 Chrome/67.0.3396.87 Mobile Safari/537.36|Samsung Internet 9.0|Samsung SM-J337W|Not good. The user-agent is good but missing the deviceId
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1|Mobile Safari 13.0|Apple iPhone|Not good. The user-agent is good but missing the deviceId

**Comment by thierryrama** [comment]
What is wanted in the User-Agent header that is being sent by the web view is:
``User-Agent: '{Existing User-Agent}' + 'DeviceId/{deviceId}``
where ``{Existing User-Agent}`` is what is set by default by just using the web view and ``{deviceId}`` is a short version of UUID with 2 check digits.

**Comment by AJBouzidi** [comment]
This is has been tested and it's working using user agent in EQ and coming form iOS device
