### ISSUE TITLE
Language change conflicts with accessing results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#119]
I enter the app and complete my first survey.  I can then access the dashboard.  
Next I went to the settings menu, and changed my language to French.  I can no longer enter the dashboard, I receive the message that says I need to complete a questionnaire submission first.  When I go to the questionnaire, it calls questionnaire B, which is correct since I've already completed questionnaire A.  Revising language cannot block access to the dashboard.

**Comment by AJBouzidi** [comment]
This is been fixed.
