### ISSUE TITLE
Secure your account: iOS picker for the list of secret questions

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#138]
The iOS and Android doesn't show the dialog in simular way. 
iOS is the problem. 
you may need to do a custom one for both OS
Example we may use. 
https://www.youtube.com/watch?time_continue=8&v=UiWgN39R9GA&feature=emb_logo
![image](https://user-images.githubusercontent.com/58231743/76254016-1a6d4400-6222-11ea-95a6-8f7d540694c0.png)

**Comment by armonkolaei** [comment]
implemented new custom component for android/ios
