### ISSUE TITLE
Reset password screen issue

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#139]
On iOS 

1. when the first time you open the app 
2. you go the forgot password screen. 
3. system will bring you back automatically to the login screen

**Comment by AJBouzidi** [comment]
this been fixed please test it again.

**Comment by armonkolaei** [comment]
@AJBouzidi this is a duplicate I already have this ticket sent to @Jiandong-Guo . please close or merge tickets

**Comment by armonkolaei** [comment]
@AJBouzidi Reset Password bouncing back to login #152 is a duplicate.

**Comment by armonkolaei** [comment]
Fixed issue by managing JavaScript execution times on bootstrap
