### ISSUE TITLE
Notification strategy issues 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#141]
-	Invalid intervals are being selected. For example, when sleep hour is 23 and awake hour is 6, many notifications were selected at 0, 1, 2, 3, 4 and 5. If the respondent goes to bed at 11pm and wakes up at 6am, they should not be receiving notifications during this time. See next point.

-	It looks like the selected intervals are being based on the awake interval but treated as a time unit. For example, if the respondent wakes up at 6am and goes to bed at 11pm then they would be awake for 17 hours so there should be 17 possible time intervals to select from (i.e., 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21 and 22). However when I ran the simulator several times, it appeared that this case only selected the following time intervals: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 and 17. The same situation happened for all the cases that I tested.

-	If the sleep hour is 0, the time intervals go up to 34. 

-	Simulator fails when respondent wakes up at an hour that is larger than the sleep hour (in terms of a 24 hour clock). For example, if someone goes to bed at 7:30pm and wakes up at 12pm the next day then the time intervals go up to 62 and no intervals were chosen for notifications. This is a top priority to implement. 

-	The one hour intervals are including the hour when the respondent goes to bed (we do not want this). If a respondent goes to bed at 23h then the last available interval should be 22h and we stop sending notifications as of 23h. 

-	It does not look like the maximum and minimum sleep intervals are being adjusted. I believe these should be reset to the defaults.

**Comment by AJBouzidi** [comment]
This is has been fixed, please reopen it if the functionality not working as expected.
