### ISSUE TITLE
Notification Strategy - time rounding 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#142]
When the awake hour is not a whole number, we should round later.  ie 07:45 should round to 8. 

When the sleep hour is not a whole number, we should round earlier. it 22:45 should round to 22:00. 

Reminder, rounding should only happen in the background of the app, not for the respondent to see.

**Comment by AJBouzidi** [comment]
This is has been fixed please reopen it if the functionality not working as expected.
