### ISSUE TITLE
Initial presentation of password requirements 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#144]
When first presented with password requirements, checkmarks should not be visible.  These should only be visible when validating the password requirements.

**Comment by AJBouzidi** [comment]
this has been done

**Comment by mullhol** [comment]
This is not implemented, if I download a new version of the app the checkmarks are still displayed on the initial requirements screen - they should only be used if the respondent selects the option to verify their password.

**Comment by mullhol** [comment]
@Jiandong-Guo The password requirements are no longer presented to the respondent when they land on the create password page. The password requirements were not to be removed, only the checkmarks beside each requirement.  The flow should be: 

1) respondent presented with password requirements
2) respondent creates password, password is live-verified on screen
3) if respondent wants to review password requirements, they click on question mark to see original requirements with checkmark verification 

![image](https://user-images.githubusercontent.com/59370537/88546410-572bb300-cfea-11ea-8bff-c3d36234f4f7.png)

![image](https://user-images.githubusercontent.com/59370537/88546443-614db180-cfea-11ea-863a-b97ffa238145.png)

![image](https://user-images.githubusercontent.com/59370537/88546477-6dd20a00-cfea-11ea-9765-3aad6f60df47.png)

**Comment by mullhol** [comment]
Implemented successfully
