### ISSUE TITLE
Terms and conditions - text formatting

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#146]
Headlines are not formatted.  Indents should be removed.  This affects both languages.  

![image](https://user-images.githubusercontent.com/59370537/76305801-357c9a00-629c-11ea-89ae-c0e0b3f42361.png)

![image](https://user-images.githubusercontent.com/59370537/76305831-40cfc580-629c-11ea-8038-13d2c0b0d5d7.png)

**Comment by AJBouzidi** [comment]
this is has been fixed

**Comment by mullhol** [comment]
Headings are not formatted.  Please refer to UX file for style. Headings include: 

Disclaimer 

General terms and conditions 

Modification of Terms and Conditions

Privacy notice

Confidentiality statement

Official language notice

Accessibility notice

Use of content

Unique identifier

Applicable law

Limitation of liability

Disclosure statement
 
Copyright notice

Trademark notice

No warranties

Indemnity 

Restrictions

Modifications and access

Ownership

Maintenance and support


Désistement

Conditions générales

Modification des conditions générales

Avis de confidentialité

Énoncé de confidentialité

Langues officielles

Avis de l’accessibiité

Utilisation du contenu

Code d’identification unique

Lois applicables

Limitation de la responsabilité

Avis de divulgations

Droit d’auteur

Avis concernant l'image de marque

Aucune garantie

Indemnité 

Restrictions
 
Modification et accès

Propriété

Maintenance et soutien

**Comment by mullhol** [comment]
Model based on UX style guide, as outlined with Contact Us page as an example

![image](https://user-images.githubusercontent.com/59370537/81950749-5cc05200-95d2-11ea-89b6-c0966a9b4303.png)

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 18th release, please reopen this issue if the functionality not working as expected.
