### ISSUE TITLE
Dashboard - percentages on overview page 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#150]
Overview screen should be numeric values as it was on speedometer view, not percentages.  

*Ali, do not action this ticket until after Wednesday's meeting with QDRC in case this change is no longer required.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo, this need to be revised. you need to add decimal point without percentage. Example 9.2, 5.6, 3.7

**Comment by Jiandong-Guo** [comment]
It is done but only can be seen after next webApi deployment

**Comment by AJBouzidi** [comment]
This is done but will be deployed with the new webAPI.
