### ISSUE TITLE
Dashboard - logo and settings menu placement 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#151]
Logo and settings cogwheel are too close to the top of the screen, impeded by time, battery, etc.  

![image](https://user-images.githubusercontent.com/59370537/76242765-990bb680-620d-11ea-8979-8ec99196412b.png)

**Comment by Jiandong-Guo** [comment]
Seems we have to remove this page into detail page. so will do it together there.  just need to make sure everything are still in the image slider not change back to Tab in old version.

**Comment by AJBouzidi** [comment]
this is has been done
