### ISSUE TITLE
Extract SAC code from Confirmation Page

### ISSUE THREAD

**Issue by thierryrama** [StatCan/wellBeingCheck#156]
After filling the Questionnaire A, the confirmation code is returned by EQ in the form of SAC-XXXXXXXXXXXXXXXX.
The purpose of the is ticket is to extract XXXXXXXXXXXXXXXX from the webview and save it in the mobile app.
The idea on how to do it is as follow:
* upon detection that the webview loaded the thank you page, we can inject a javascript that will inspect the html document in the webview and find where the SAC is
* use postMessage to get it from the webview to the mobileapp

**Comment by thierryrama** [comment]
The confirmation number right now is in ``html/body/main/div[class="sc-box-main"]/p/span[class="ecf-bold"]``.
We can navigate the dom to get to the confirmation number using javascript injected to the webview that will post the extracted conf# back to the mobile app.

**Comment by thierryrama** [comment]
If we can get to a script element from navigating the DOM, the confirmation number is also part of the script with ``window.postMessage('SAC-XXXXXXXXXXXXXX'')``. That is probably easier to get if possible.

**Comment by Jiandong-Guo** [comment]
the confirmation # is like W000-0001-9886

**Comment by thierryrama** [comment]
For now, if you can extract whatever is in the confirmation number, either SAC-XXXXX or W-XXX-YYYY-ZZZZ then we are good. What is important is getting data from that thank you page.

**Comment by Jiandong-Guo** [comment]
Yes I can extract it from Thank you page by a little trick but seems the thank you page will show little longer. before it flashes 2 seconds but now may stay there 5 seconds

**Comment by AJBouzidi** [comment]
this is has been done
