### ISSUE TITLE
Relationship between wake up time and bedtime

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#160]
I set the wake up time. 
I set the bedtime. 
If I click on wake up time again to further revise the time, the wheel is showing the same time as the bedtime. It should show the wake up time. 

In subsequent tests, when I clicked on the wake up time it showed the current time.

**Comment by AJBouzidi** [comment]
@mullhol check this please

**Comment by mullhol** [comment]
@AJBouzidi This is still an issue. I set the awake time to 8:45 and selected "confirm". When I open the picker again, the wheels are on the current time (12:43) - they should remain at 8:45 until physically changed.

**Comment by mullhol** [comment]
I am no longer having this issue, the time picker now opens to the times it was set to.
