### ISSUE TITLE
Show/hide password 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#164]
This functionality should also be on the confirm password field and the enter password field for second entry

**Comment by armonkolaei** [comment]
@AJBouzidi Are you saying the eye icon has to be in the confirm password filed as well.
If so, that should not be the case. The confirm password is usually hidden so users do not enter the password by what they see above or copy/paste. This is standard so the user is aware of what they are entering by making enter the password correctly without mistakes and cap locks.

Lets discuss this in the morning.

**Comment by armonkolaei** [comment]
@mullhol add show/hide for confirm password on registration screen. (Same button)
Add show/hide functionality for Login screen
