### ISSUE TITLE
Settings menu in dashboard kicks you back to login 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#165]
There is a bug in the settings menu of the dashboard.  
Current path : Results - Settings - Return - login page. 
You should not be returned to the login page.

**Comment by Jiandong-Guo** [comment]
@AJBouzidi 1)in andriod, I can not see the return button, 2)where should go when click this button ?

**Comment by Jiandong-Guo** [comment]
modified and In master

**Comment by AJBouzidi** [comment]
the Return Button on the setting screen not working properly in iOS.

**Comment by AJBouzidi** [comment]
this is has been done
