### ISSUE TITLE
Manage Timeout

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#17]
The application should be timeout after 15 min of non-activity

**Comment by AJBouzidi** [comment]
![Time-out](https://user-images.githubusercontent.com/58231743/79716971-46122e00-82a6-11ea-878a-83e5404dc6fc.PNG)
![Time-out signin again](https://user-images.githubusercontent.com/58231743/79716972-46122e00-82a6-11ea-87a0-898d55fc16a0.PNG)
![Time-out-fr](https://user-images.githubusercontent.com/58231743/79716973-46122e00-82a6-11ea-8adc-5c7a06d43c96.PNG)
![Time-out signin again-fr](https://user-images.githubusercontent.com/58231743/79716974-46aac480-82a6-11ea-9e38-eb622e8055bf.PNG)

**Comment by armonkolaei** [comment]
@AJBouzidi we don't have a way of continuing session. having said that the text mentioned above is grammatically incorrect to use.

This is what i have right now: 
Session expired
Your session has expired due to 15 minutes of inactivity

if this text is good I need the french translation.

**Comment by armonkolaei** [comment]
![Screenshot_20200421-031742](https://user-images.githubusercontent.com/7444938/79836985-ca37e480-837e-11ea-8107-be452579538d.jpg)

**Comment by AJBouzidi** [comment]
@armonkolaei in this case the second message will work. 
![timeout-en](https://user-images.githubusercontent.com/58231743/79902205-1450b280-83df-11ea-92c2-ac8db31d1f8f.png)
![timeout-fr](https://user-images.githubusercontent.com/58231743/79902206-14e94900-83df-11ea-95d7-3ea91a8692ca.png)

**Comment by armonkolaei** [comment]
all internal screens after login now have session time out of 7 minutes

**Comment by AJBouzidi** [comment]
we need to add time out to the main screen.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 8th release, please reopen it if the functionality not working as expected.
