### ISSUE TITLE
Language not saving after closing app 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#172]
Entered app, revised language to French in settings menu.  Fully exited app.  When opened for the second time, it opened in English.  It should be in French to respect the settings I previously altered.

**Comment by AJBouzidi** [comment]
@armonkolaei  I figure-out that the problem caused on the launch screen because we only validate the Localization.Locale. I added the also app culture and it's working now.

**Comment by AJBouzidi** [comment]
This has been fixed and will be delivered in the release of  May 4th.
