### ISSUE TITLE
Swipe in results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#175]
To swipe screens in the results menu, you need to swipe across the entire screen of the phone or the previous page bounces back onto the screen. How can we make this easier to swipe?

**Comment by Jiandong-Guo** [comment]
You have to swipe over 50% of its width to change to next page,   basically it is "press finger, move and release finger"

**Comment by armonkolaei** [comment]
@mullhol is this on ios, android or both?
@Jiandong-Guo the Swipe functionality should be either native (we cannot modify) or controlled by the plugin we are using not sure if we are please let me know.
Also another solution is to introduce chevron slider buttons.

**Comment by armonkolaei** [comment]
@Jiandong-Guo you mentioned you can have a look at this so assigning to you.

**Comment by mullhol** [comment]
@armonkolaei It's on iphone for certain, @AJBouzidi can you confirm if it is an issue on Android as well?

**Comment by AJBouzidi** [comment]
@armonkolaei @mullhol  for both.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 4th release, please reopen it if the functionality not working as expected.
