### ISSUE TITLE
Update the minimum targeted OS version

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#185]
Update the minimum required version of iOS and Android that the user needs to download the wellbeingcheck mobile application

**Comment by AJBouzidi** [comment]
this on hold will be done when we do the final release

**Comment by zhuelle** [comment]
@AJBouzidi can you please put more details on what we need to do for this ticket? I am wondering why we have to wait until final release to tackle this ticket?

**Comment by AJBouzidi** [comment]
@zhuelle as discussed in the meeting this need to be addressed  before the release to production and based on the market share. 
iOS 12 or 13 and up and Android 8 or 10 and up at this moment.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo has this been reviewed?

**Comment by Jiandong-Guo** [comment]
The minimum target OS:
      Android 8.0
      iOS 13.3
