### ISSUE TITLE
Bug in settings menu (opening dashboard)

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#187]
I downloaded the app and agreed to receive notifications.  I flowed through the entry process and completed a questionnaire.  I went to settings and changed my wake up and bedtime.  Exited menu to see if settings saved (they did).  Went back in settings and turned off notifications.  Exited settings to see if this change saved - it did also (yay!).  But when I went back into settings, I swiped out of the settings screen to the homepage.  The homepage was visible for about 2 seconds, then the dashboard popped open without me touching anything. 

This may be resolved by eliminating the swipe option as requested in previous ticket, but important to note regardless. Video of bug available on uat_well-being-check_testing_video slack channel.

**Comment by AJBouzidi** [comment]
this is has been fixed
