### ISSUE TITLE
Eliminate swiping out of menus/homepage

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#188]
The respondent should not be able to swipe to exit menus. Currently, they can swipe out of the settings menu, info menu,  contact us menu, and the results menu.  

In addition, I was able to swipe off the homepage through the entire entry flow of the app - from homepage to secure account, to T&C, to Getting Started, to the splash page.  I was then stuck on the splash page until I exited the app completely.  

Please eliminate all swiping - the respondent must use return buttons to navigate out of menus.

**Comment by armonkolaei** [comment]
removed ios swipe left functionality from all screens
