### ISSUE TITLE
info menu - unable to scroll through all text 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#189]
When in the info menu, I'm unable to scroll through all of the text. I can only scroll as far as the end of the session timeout section (cutting off the definitions and explanation section). When the FAQ are open, I can scroll through even less.

**Comment by armonkolaei** [comment]
fixed scroll issue

**Comment by mullhol** [comment]
Rachel is currently experiencing a version of this issue.  "My phone sometimes has difficulty scrolling in the QA section. Has anyone else experienced this? When I open one of the lowest level drop down boxes (the actual question) and the response does not entirely fit on my screen, the screen is sometimes unresponsive to scrolling."

She is using a Pixel 3 on Android 11.

**Comment by AJBouzidi** [comment]
@mullhol This issue happen because of the time out of the mobile application.. when the phone has a low memory the timer will affect the phone performance.

**Comment by zhuelle** [comment]
@AJBouzidi Please document the issues and let business to make decision

**Comment by Jiandong-Guo** [comment]
Close it according Trish's email
