### ISSUE TITLE
Revision to wake up and bedtime settings 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#191]
It was determined in QDRC Testing that despite explanations provided throughout the app and other comm materials, respondents were not reading instructions and did not understand the wake-up time and bedtime in the settings menu. Could we revise this to "do not disturb". I expect this requires development of an additional screen to set the times (based on the function in iOS's settings) 

![image](https://user-images.githubusercontent.com/59370537/77681553-dc835600-6f6b-11ea-83ad-9ec62bc13ae6.png)

![image](https://user-images.githubusercontent.com/59370537/77681900-70edb880-6f6c-11ea-85ac-04d64f99926d.png)

![image](https://user-images.githubusercontent.com/59370537/77681957-8236c500-6f6c-11ea-9607-3afbc201d1f5.png)

![image_from_ios](https://user-images.githubusercontent.com/58231743/77687868-81566100-6f75-11ea-97bc-b13eee6e5514.jpg)

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 11th release, 
please reopen it if the functionality not working as expected.
