### ISSUE TITLE
Settings menu - difficulty opening when notifications are turned off 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#194]
I downloaded the app and agreed to receive notifications. I went through entry flow, then went to settings menu to revise my settings - revised wake up time, bedtime, and turned notifications off.  Exited the settings menu.  when I tried to re-enter the settings menu, I had to make numerous attempts.  The settings menu would flash and then disappear.  This happened on approximately 2/3 attempts.  Seems to be related to notifications being turned off - could not replicate when notifications are turned on.  

Video of bug available if required.

**Comment by AJBouzidi** [comment]
This has been fixed.

**Comment by AJBouzidi** [comment]
@armonkolaei this is still happen.

**Comment by armonkolaei** [comment]
@AJBouzidi can you please retest.

**Comment by mullhol** [comment]
@armonkolaei @AJBouzidi 
Tested well for me this evening, doesn't seem to be an issue now.

**Comment by AJBouzidi** [comment]
Working as expected. please reopen this ticket if the functionality not working.
