### ISSUE TITLE
Notifications Alert content 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#195]
Remove the heading "Notification Alerts", and change the alert content to:
Visit your device settings to enable notifications
Accédez aux paramètres de votre appareil pour activer les notifications

![image](https://user-images.githubusercontent.com/59370537/77968253-e3d09980-72b4-11ea-934b-c393776c6542.png)

**Comment by AJBouzidi** [comment]
This is been fixed will be available in the 27th April release
