### ISSUE TITLE
screenshots and video for App Stores

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#196]
App Screenshots and videos:
The promotional videos, in App Store we can upload a promotional video but on google play store we have to provide a link of the video. 

1. Apple store : https://developer.apple.com/support/app-previews/

3. Google play Store: https://support.google.com/googleplay/android-developer/answer/1078870?hl=en

5. stores screenshots specifictions: https://confluence.statcan.ca/pages/viewpage.action?pageId=886871644

**Comment by mullhol** [comment]
For now, I would use:
1) splash page
2) homepage
3) Questionnaire B Q1
4) Questionnaire B Q6
5) Questionnaire B Q8 
6) Dashboard overview 
7) Dashboard feelings by location 

For the questionnaire screen shots, I would screen shot them without the progress bar so more of the question itself if visible.

**Comment by mullhol** [comment]
Request to further discuss has been submitted to COMM via Marc Bazinet's team. No response to date due to priority issues.

**Comment by mullhol** [comment]
Update: I spoke with Marc Bazinet from communications this morning. His team will prepare graphics for us. We agreed video would not be necessary for the pilot. This work hinges on the questionnaire and app being complete, so we agreed to touch base late August for his team to stat the work

**Comment by mullhol** [comment]
Here are the graphics for the app stores in both English and French: https://gcdocs.gc.ca/statcan/llisapi.dll/link/12110563 

@Jiandong-Guo

**Comment by Jiandong-Guo** [comment]
All the screen shots were uploaded to stores
