### ISSUE TITLE
Methodologist Testing - min/max sleep intervals and defaults 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#198]
- If respondent goes to be at 9am and wakes up at 6am then they get pinged during time when they would be sleeping… this might be related to the defaults. See next point. 
- It still does not look like the minimum and maximum sleep intervals are being applied. Are these supposed to restore to the defaults?

**Comment by AJBouzidi** [comment]
@mullhol check this please.

**Comment by Jiandong-Guo** [comment]
The algorithm had changed already
