### ISSUE TITLE
Notifications: Algorithm Implementation

### ISSUE THREAD

**Issue by saqib-dareshani** [StatCan/wellBeingCheck#2]
[Methodology_Specs_Ping.docx](https://github.com/StatCan/experimental-react-native-app/files/4000672/Methodology_Specs_Ping.docx)

-Testing upto Selection Probabilities
-modify the algorithm to use the screen paramaters

**Comment by AJBouzidi** [comment]
this has been implemented in part, for the remain work use https://github.com/StatCan/wellBeingCheck/issues/35
