### ISSUE TITLE
Methodologist Testing - invalid intervals

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#200]
- Invalid intervals are still being selected for some cases. For example, if the respondent goes to bed 19h and wakes up at 12h then they were pinged at 19h, 20h and 22h. 

@saqib-dareshani 
![IMG_0039](https://user-images.githubusercontent.com/58231743/79339651-30dc7e80-7ef7-11ea-90db-6ce60197993d.PNG)
![IMG_0052](https://user-images.githubusercontent.com/58231743/79340137-dd1e6500-7ef7-11ea-831e-ae08c5d3a20f.PNG)

**Comment by AJBouzidi** [comment]
The Edges of the Notifications algorithm still not working:
This is testing with default value: 
error on day 4, day 8, day 23, : 

Chosen   Hours for Day: 4
9,17,18,22,20

Chosen   Hours for Day: 8
22,15,18,12,8

Chosen Hours for   Day: 23
17,22,16,21,20







Output:
The awake hour is: 6
The sleep hour is: 22
The num pings are: 5

One Hour Time Intervals
7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
7,8,9,10,11,12,13,14,15,16,17,18,19,20,21

Length of awake hour array is: 15

Length of selection probabilities array is: 24

Chosen One Hour Time Intervals (24h format):
---------------------------------------------------------

Adding selection probability: 4% at position (24h time): 10
Adding selection probability: 5% at position (24h time): 11
Adding selection probability: 5% at position (24h time): 12
Adding selection probability: 5% at position (24h time): 13
Adding selection probability: 5% at position (24h time): 14
Adding selection probability: 5% at position (24h time): 15
Adding selection probability: 4% at position (24h time): 16
Adding selection probability: 5% at position (24h time): 17
Adding selection probability: 10% at position (24h time): 18
Adding selection probability: 13% at position (24h time): 19
Adding selection probability: 15% at position (24h time): 20
Adding selection probability: 12% at position (24h time): 21
Adding selection probability: 6% at position (24h time): 22
Adding selection probability for weekends: 4% at position (24h time): 10
Adding selection probability for weekends: 5% at position (24h time): 11
Adding selection probability for weekends: 8% at position (24h time): 12
Adding selection probability for weekends: 10% at position (24h time): 13
Adding selection probability for weekends: 11% at position (24h time): 14
Adding selection probability for weekends: 8% at position (24h time): 15
Adding selection probability for weekends: 7% at position (24h time): 16
Adding selection probability for weekends: 5% at position (24h time): 17
Adding selection probability for weekends: 7% at position (24h time): 18
Adding selection probability for weekends: 9% at position (24h time): 19
Adding selection probability for weekends: 9% at position (24h time): 20
Adding selection probability for weekends: 7% at position (24h time): 21
Adding selection probability for weekends: 4% at position (24h time): 22
Output of selection probabilities array is: ,,,,,,,,,,4,5,8,10,11,8,7,5,7,9,9,7,4,

Length of selection probabilities array is: 24

Probabilities remaining to be allocated: 6%
Probabilities remaining to be allocated for weekends: 6%
The selection probability array is: ,,,,,,,3,3,3,4,5,5,5,5,5,4,5,10,13,15,12,6,
Validate: The sum of the selection probability array is: 103%
The selection probability array is: ,,,,,,,3,3,3,4,5,8,10,11,8,7,5,7,9,9,7,4,
Validate: The sum of the selection probability weekends array is: 103%
Current Offset Date is: Tue Apr 14 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 2
It's a Weekday
Chosen Probabilities (0-100) for Day: 1
73,51,57,81,16
Chosen Hours for Day: 1
20,18,19,15,11
Current Offset Date is: Wed Apr 15 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 3
It's a Weekday
Chosen Probabilities (0-100) for Day: 2
90,58,91,49,57
Chosen Hours for Day: 2
21,13,20,18,19
Current Offset Date is: Thu Apr 16 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 4
It's a Weekday
Chosen Probabilities (0-100) for Day: 3
47,76,26,27,78
Chosen Hours for Day: 3
9,16,13,21,20
Current Offset Date is: Fri Apr 17 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 5
It's a Weekday
Chosen Probabilities (0-100) for Day: 4
6,80,51,99,79
Chosen Hours for Day: 4
9,17,18,22,20
Current Offset Date is: Sat Apr 18 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 6
It's a Weekend
Chosen Probabilities (0-100) for Day: 5
14,72,77,66,11
Chosen Hours for Day: 5
11,19,10,17,13
Current Offset Date is: Sun Apr 19 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 0
It's a Weekend
Chosen Probabilities (0-100) for Day: 6
78,19,85,25,50
Chosen Hours for Day: 6
12,14,20,19,15
Current Offset Date is: Mon Apr 20 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 1
It's a Weekday
Chosen Probabilities (0-100) for Day: 7
13,67,85,32,84
Chosen Hours for Day: 7
11,13,21,14,20
Current Offset Date is: Tue Apr 21 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 2
It's a Weekday
Chosen Probabilities (0-100) for Day: 8
97,75,47,56,3
Chosen Hours for Day: 8
22,15,18,12,8
Current Offset Date is: Wed Apr 22 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 3
It's a Weekday
Chosen Probabilities (0-100) for Day: 9
32,82,81,83,93
Chosen Hours for Day: 9
14,20,15,19,21
Current Offset Date is: Thu Apr 23 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 4
It's a Weekday
Chosen Probabilities (0-100) for Day: 10
85,1,92,46,0
Chosen Hours for Day: 10
12,7,18,17,21
Current Offset Date is: Fri Apr 24 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 5
It's a Weekday
Chosen Probabilities (0-100) for Day: 11
26,57,88,3,13
Chosen Hours for Day: 11
13,19,7,8,11
Current Offset Date is: Sat Apr 25 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 6
It's a Weekend
Chosen Probabilities (0-100) for Day: 12
26,33,45,84,36
Chosen Hours for Day: 12
13,16,14,20,17
Current Offset Date is: Sun Apr 26 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 0
It's a Weekend
Chosen Probabilities (0-100) for Day: 13
11,74,14,20,47
Chosen Hours for Day: 13
10,19,11,12,15
Current Offset Date is: Mon Apr 27 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 1
It's a Weekday
Chosen Probabilities (0-100) for Day: 14
30,75,64,51,63
Chosen Hours for Day: 14
14,20,19,18,16
Current Offset Date is: Tue Apr 28 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 2
It's a Weekday
Chosen Probabilities (0-100) for Day: 15
17,41,65,91,83
Chosen Hours for Day: 15
11,14,19,21,20
Current Offset Date is: Wed Apr 29 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 3
It's a Weekday
Chosen Probabilities (0-100) for Day: 16
49,75,26,70,21
Chosen Hours for Day: 16
18,17,13,21,12
Current Offset Date is: Thu Apr 30 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 4
It's a Weekday
Chosen Probabilities (0-100) for Day: 17
3,86,67,56,36
Chosen Hours for Day: 17
8,11,19,18,15
Current Offset Date is: Fri May 01 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 5
It's a Weekday
Chosen Probabilities (0-100) for Day: 18
66,26,39,57,23
Chosen Hours for Day: 18
7,13,16,19,8
Current Offset Date is: Sat May 02 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 6
It's a Weekend
Chosen Probabilities (0-100) for Day: 19
44,61,74,25,52
Chosen Hours for Day: 19
14,7,17,12,15
Current Offset Date is: Sun May 03 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 0
It's a Weekend
Chosen Probabilities (0-100) for Day: 20
35,93,77,69,5
Chosen Hours for Day: 20
13,21,19,18,8
Current Offset Date is: Mon May 04 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 1
It's a Weekday
Chosen Probabilities (0-100) for Day: 21
11,52,28,77,92
Chosen Hours for Day: 21
10,15,14,20,21
Current Offset Date is: Tue May 05 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 2
It's a Weekday
Chosen Probabilities (0-100) for Day: 22
0,93,67,12,58
Chosen Hours for Day: 22
7,13,19,10,9
Current Offset Date is: Wed May 06 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 3
It's a Weekday
Chosen Probabilities (0-100) for Day: 23
68,99,39,93,76
Chosen Hours for Day: 23
17,22,16,21,20
Current Offset Date is: Thu May 07 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 4
It's a Weekday
Chosen Probabilities (0-100) for Day: 24
44,37,16,90,11
Chosen Hours for Day: 24
17,15,11,21,10
Current Offset Date is: Fri May 08 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 5
It's a Weekday
Chosen Probabilities (0-100) for Day: 25
32,88,92,36,94
Chosen Hours for Day: 25
14,18,20,15,21
Current Offset Date is: Sat May 09 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 6
It's a Weekend
Chosen Probabilities (0-100) for Day: 26
1,39,86,92,89
Chosen Hours for Day: 26
7,14,20,18,13
Current Offset Date is: Sun May 10 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 0
It's a Weekend
Chosen Probabilities (0-100) for Day: 27
54,19,51,85,12
Chosen Hours for Day: 27
15,12,20,17,10
Current Offset Date is: Mon May 11 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 1
It's a Weekday
Chosen Probabilities (0-100) for Day: 28
58,90,78,22,56
Chosen Hours for Day: 28
19,21,20,12,18
Current Offset Date is: Tue May 12 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 2
It's a Weekday
Chosen Probabilities (0-100) for Day: 29
26,5,46,61,40
Chosen Hours for Day: 29
13,8,17,19,16
Current Offset Date is: Wed May 13 2020 22:17:31 GMT-0400 (Eastern Daylight Time)
Current Day is: 3
It's a Weekday
Chosen Probabilities (0-100) for Day: 30
41,68,89,38,15
Chosen Hours for Day: 30
9,18,21,20,11

**Comment by mullhol** [comment]
Updated comment from Amanda: 
I did notice something strange with the 2nd point below though (i.e., goes to bed at 19h and wakes up at noon). Previously, the respondent would be pinged at invalid intervals, now the available intervals are going up to 64 (i.e., 20, 21, 22, …. 64). It doesn’t seem to be accounting for the 24h clock (but the last version did).

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 18th release, 
please reopen it if the functionality not working as expected.
