### ISSUE TITLE
Notification algorithm scheduling

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#205]
- The Notification Algorithm will start after the user finishes Survey A ( socio-demographic + wellbeingcheck) at handleSurveyAdone(){} in EqSurveyScreen.  The settings screen cannot trigger the start of the notification algorithm. 

- Notifications are to be scheduled for 4 days at a time.  If the user does not complete a survey B submission within 4 days, we will send one additional notification on day 5 saying  (We haven’t heard from you in a while. Sign in for a Well-being Check!, Nous n’avons pas eu de vos nouvelles depuis un certain temps. Connectez-vous pour obtenir un Bilan bien-être!).

- If the user still does not complete a Survey B submission, we will stop sending the user notifications and not schedule the next round of 4 days.  This respects a decision by OPMIC, SM and CPRD based on respondent burden practices and current collection reminder strategies.  

- The user can receive notifications for a maximum of 30 days from the day they complete Survey A 
 (survey A + 29 days). 

- The Notification will be forecasted for 4 days. Always 4 days of Notification on the queue. 

- If the user skips a day and doesn't complete a survey, that day will be included in the 30 days.

- The "last attempt" notification (if the respondent has not completed a survey after 4 days of notifications) should be sent to the respondent on day 5, two hours before bedtime.

**Comment by Jiandong-Guo** [comment]
Is there a specific time frame to send additional notification on day 5 saying (We haven’t heard from you in a while. Sign in for a Well-being Check!, Nous n’avons pas eu de vos nouvelles depuis un certain temps. Connectez-vous pour obtenir un Bilan bien-être!)  if the user does not finish a survey B at least once within the last 4 days?

**Comment by mullhol** [comment]
This question was sent to Subject Matter and Methodology for a decision the morning of April 21. I will update once a decision has been reached.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo  the notification on the 5 day is two hours before bedtime.

**Comment by Jiandong-Guo** [comment]
it was fixed in new algorithm
