### ISSUE TITLE
Maximum sleep interval not respected 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#209]
I was able to revise my settings menu to wake up time 8:30am, and sleep time 10:45am.  This does not respect the sleep interval of maximum 14 hours and prevented me from being able to receive notifications. 

From methodology's specifications: 
-	Maximum sleep interval: 14 hours 
-	Minimum sleep interval: 2 hours 
sleep_hour = time when respondent goes to bed (default is 22h or 10pm)
awake_hour = time when respondent wakes up (default is 6h or 6am)
awake_interval = number of hours respondent is awake = sleep_hour - awake_hour (default is 16 hours)

![image](https://user-images.githubusercontent.com/59370537/78795903-91ae0900-7983-11ea-8953-1c2215709b2d.png)

**Comment by Jiandong-Guo** [comment]
validation function was added before exit the setting page
