### ISSUE TITLE
Electornic Questionnaire Question Scale

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#220]
The scale of question in the questionnaire B should be changed from 0 to 1 to be able to show the bar graph

**Comment by mullhol** [comment]
The questionnaire will be revised to a scale of 1-10 once OID is available to work on the project again.

**Comment by mullhol** [comment]
After further discussion, we have implemented a revision to the results dashboard to demonstrate a thin line when a value is zero. This will signal to the respondent that there is a sentiment to be displayed, but they have not reported a value above 0 yet. As such, we will keep the scale of 0-10 on the questionnaire which is better for methodological purposes.
