### ISSUE TITLE
Questionnaire B-CMP 

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#221]
The changes in labelling leads to changes in columns and this is affecting CMP backend Processing

**Comment by mullhol** [comment]
Question 8 will be re-ordered to match the processing specifications once OID is available to work on the project again. No revisions to the processing strategy will be required as a result.

**Comment by mullhol** [comment]
This ticket it on hold until EQ revisions have been made.

**Comment by mullhol** [comment]
Update: EQ revisions expected to be implemented and signed off August 25th. We will be able to connect to the revised EQ and test the output of Q8 at that time.

**Comment by mullhol** [comment]
Questionnaire B has been revised and is ready for inclusion and testing.
