### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by armonkolaei** [StatCan/wellBeingCheck#223]
Internet connection unavailable

Access denied(Config), Try it later, if same thing would happen again contact StatCan

Access denied, Try again later, if same thing would happen again contact StatCan

Internet connection unavailable

All these texts are in dashbaord/home screen so and they are triggered on error as alert popup

we need proper English and french text

**Comment by AJBouzidi** [comment]
This has been fixed, please reopen this issue if the functionality not working as expected.
