### ISSUE TITLE
Android/iOS timepicker language

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#225]
When we switch the french language the time picker still in english.

**Comment by mullhol** [comment]
@AJBouzidi Works in current version

**Comment by AJBouzidi** [comment]
@mullhol this is has been fixed in iOS but in Android, if the app in french and OS in english the time picker still in English.

**Comment by mullhol** [comment]
This has been resolved with development of a custom android solution.  Thanks @Jiandong-Guo !
