### ISSUE TITLE
Stores localisation text

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#227]

**Comment by mullhol** [comment]
[WB_App_Store_Specs_eng.DOCX](https://github.com/StatCan/wellBeingCheck/files/4599737/WB_App_Store_Specs_eng.DOCX)
[WB_App_Store_Specs_fre.DOCX](https://github.com/StatCan/wellBeingCheck/files/4599738/WB_App_Store_Specs_fre.DOCX)

**Comment by mullhol** [comment]
Master files saved on GCDocs at:

WB_App_Store_Specs_eng.DOCX
https://gcdocs.gc.ca/statcan/llisapi.dll/link/9252702

WB_App_Store_Specs_fre.DOCX
https://gcdocs.gc.ca/statcan/llisapi.dll/link/9263497

**Comment by AJBouzidi** [comment]
Have has been received.

**Comment by mullhol** [comment]
@Jiandong-Guo
