### ISSUE TITLE
Subject Matter Testing - received notification at wrong time 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#229]
When Joelle completed and submitted questionnaire A, she immediately received a notification asking she complete questionnaire B. She should not have received this notification for at least an hour after submitting questionnaire B.  She is an android user.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo first Notification must be at least one our after survey A done.

**Comment by AJBouzidi** [comment]
@mullhol could you confirm this is has been fixed?

**Comment by mullhol** [comment]
@AJBouzidi I think this can be closed, Joelle has not noted further instances

**Comment by Jiandong-Guo** [comment]
Yes, It is a problem for old algorithm function, it doesn't have this issue in new function

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 11th release, 
please reopen it if the functionality not working as expected.
