### ISSUE TITLE
Thank you toast 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#230]
There need to be two thank you toasts.  

**1) thank you toast after respondent completes questionnaire A.  Content as follows:** 

Thank you for completing this survey! 
Nous vous remercions d’avoir participé à l’enquête! 

**2) thank you toast after respondent completes questionnaire B. Content as follows:** 

Thank you for completing this survey! You can review your Well-being Check in the Results menu.
Nous vous remercions d’avoir participé à l’enquête! Vous pouvez consulter votre Bilan bien-être dans le menu Résultats.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the release of  may 4th
