### ISSUE TITLE
Decline Message: Phone number 

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#232]
the phone number on the  decline message needs to have tap option

**Comment by mullhol** [comment]
This message used to be a small box which showed up on the T&C screen.  For some reason when the phone number changed to a tappable number, the message is now on it's own screen.  It needs to return to the original format (presented the same as the notification requesting you accept or decline notifications), but with tappable phone number.  

![image](https://user-images.githubusercontent.com/59370537/88545472-08c9e480-cfe9-11ea-93f9-6e53ec3a02a8.png)
 @Jiandong-Guo

**Comment by Jiandong-Guo** [comment]
Because the alert popup message is only be able to display string text, can not display link, so we use a separate page to display this message,   If it is not met the requirement, we have to spend time to write our own alert message popup.

**Comment by mullhol** [comment]
@Jiandong-Guo My preference would be to write our own alert message. What is the effort required?

**Comment by Jiandong-Guo** [comment]
@mullhol Will try to finish it in next release

**Comment by mullhol** [comment]
While I can now see a pop-up when I decline the T&C, I cannot see all of the content and there is no "ok" option to clear the message.  The only way I can move on is to crash the app.  Can we have another look at this? @Jiandong-Guo 

![image](https://user-images.githubusercontent.com/59370537/89655848-af8b6c00-d898-11ea-8719-0443f316bbf4.png)

**Comment by Jiandong-Guo** [comment]
@AJBouzidi  It was fixed and please test in ios first in your side, then test in next release

**Comment by mullhol** [comment]
confirmed implemented
