### ISSUE TITLE
Application FAQ

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#234]

**Comment by mullhol** [comment]
@AJBouzidi 
Here are the FAQ for the app info menu.  There will be updates required at a later date - links will need to be embedded when they are created, and additional FAQ may need to be added at a later date as those less familiar with the app have tested it (ie, after the beta test with cost recovery clients).  This is a solid base however.  

[WB_FAQ in app_eng.docx](https://github.com/StatCan/wellBeingCheck/files/4682891/WB_FAQ.in.app_eng.docx)

[WB_FAQ in app_fre.docx](https://github.com/StatCan/wellBeingCheck/files/4682892/WB_FAQ.in.app_fre.docx)

Master files located here: 
WB_FAQ in app_eng.docx
https://gcdocs.gc.ca/statcan/llisapi.dll/link/9428462

WB_FAQ in app_fre.docx
https://gcdocs.gc.ca/statcan/llisapi.dll/link/9417744

**Comment by mullhol** [comment]
FAQ have been successfully implemented to the app as provided to IT. Waiting for SM to generate links required to complete the FAQ.  This ticket will remain on hold with no work for IT until links have been provided.

**Comment by AJBouzidi** [comment]
this ticket linked to https://github.com/StatCan/WellbeingCheckUAT/issues/211

**Comment by mullhol** [comment]
Completed
