### ISSUE TITLE
 Devices compatibility guidelines

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#235]
Data uses of the application on the iOS and Android:

- IPhone: Wellbeing check taking 52.4 MB on storage
On your iPhone, go to: 
Settings > General > Storage & iCloud Usage>Manage Storage> 
under mange storage you will find the size used by the Wellbeing check mobile app. 
- Android: Wellbeing check taking 89.27 MB  on storage

Memory uses of the application on the iOS and Android:

**Comment by mullhol** [comment]
Thanks, added to the FAQ documentation for comm review.
