### ISSUE TITLE
Settings messages

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#236]
We need a message for :
if the user set less than 3hours or more than 14 hours.

**Comment by AJBouzidi** [comment]
![Simulator Screen Shot - IPhone 6 - 2020-05-21 at 23 09 51](https://user-images.githubusercontent.com/58231743/82673346-b4cd0900-9c0f-11ea-9f52-b66f51e236fe.png)
![Simulator Screen Shot - IPhone 6 - 2020-05-21 at 23 10 30](https://user-images.githubusercontent.com/58231743/82673348-b5659f80-9c0f-11ea-8b91-f06cd085158c.png)

**Comment by mullhol** [comment]
@AJBouzidi 
Are we able to customize the message based on the error?  So we have one message for 3, and a second for 14?

**Comment by AJBouzidi** [comment]
@mullhol we have only the check for 3 hours. if you want the check for 14 hours  it's can be added with the proper message.

**Comment by mullhol** [comment]
@AJBouzidi Let me check with methodology if they feel the 14 hours is required.  

In the interim, here is the content for the current check of 3 hours minimum: 

There needs to be a minimum of 3 hours between the ‘Do not disturb before’ and ‘Do not disturb after’ time settings.

Il doit y avoir un minimum de 3 heures entre les réglages « Ne pas déranger avant » et « Ne pas déranger après ».

**Comment by mullhol** [comment]
@AJBouzidi 
Methodology does not feel we need a check for the 14 hour max. Per Amanda: 
"I don’t think a check is necessary. We need them to be awake for at least 2 hours so we can send them 2 notifications. If they are awake for all 24 hours of the day, the most we are sending them is 5, so that’s fine in my opinion."

We can monitor to see if there are any issues with this approach during the beta test, but for now the check on the minimum 3 hours will be sufficient.  This ticket can be closed once the content is embedded.

**Comment by mullhol** [comment]
@AJBouzidi 

here is the content for the current check of 3 hours minimum:

There needs to be a minimum of 3 hours between the ‘Do not disturb before’ and ‘Do not disturb after’ time settings.

Il doit y avoir un minimum de 3 heures entre les réglages « Ne pas déranger avant » et « Ne pas déranger après ».

**Comment by AJBouzidi** [comment]
@mullhol in this ckeck we did a hard edit. if the condition not met then nothing will be saved. the user has 2 choices. increase the time of leave a default if he dismiss the application. is this the right way or needs to be changed.

**Comment by mullhol** [comment]
@AJBouzidi I think it would be best if we only modify their do not disturb after time so it respects the 3 hour limit.  

ie, if they select do not disturb before 8:00, and do not disturb after 10:00, we revise the 10:00 to 11:00.  Then it's in their hands if they wish to modify further.  This way we're only accommodating the minimum and they only need to decide to revise one setting.  If we revert to the default, we force them to revise two settings which is more burden on them, or turn off notifications altogether which we want to avoid.

**Comment by mullhol** [comment]
Confirmed implemented.
