### ISSUE TITLE
Receiving 5 categories in results 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#239]
I have 5 categories in my results menu for both "by activity" and "by location". Is this simply a function of not having prioritization built in yet, or a larger issue? 

![image](https://user-images.githubusercontent.com/59370537/80933263-fc8b0e00-8d90-11ea-9b78-c9f052f20c29.png)

![image](https://user-images.githubusercontent.com/59370537/80933278-0f054780-8d91-11ea-81b5-e55500b75603.png)

**Comment by AJBouzidi** [comment]
this is will be related to priority graph issue. 
https://github.com/StatCan/wellBeingCheck/issues/222
