### ISSUE TITLE
Cloud server set up

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#24]
The purpose of this task is to install a custom version of the CMP/EQ infrastructure on a cloud server to allow testing the mobile app on a real device since we cannot connect the mobile phones on StatCan network.
It will require:
- a version of CMP running on an embedded database on which we can configure the anonymous ESM survey and provides the webservices required by EQ to open an anonymous questionnaire
- an anonymous test version of the EQ Portal that only relies on CMP and no other webservices to host two questionnaires that we will use as QuestionnaireA and Questionnaire B

**Comment by thierryrama** [comment]
After battling with errors and out of date settings, a version of CMP/EQ now runs on an azure cloud machine accessible to the internet. 
The link to the questionnaire is at http://barabasy.eastus.cloudapp.azure.com/
The machine is supposed to run 24h/day and has two questionnaires (A&B) deployed.
CMP is not accessible from the internet but all responses submitted through the questionnaires are collected in a database.
Observations:
* the questionnaires are slow to load. We have to check with EQ team for that
* the questionnaires are not final version and we need to look at how they render inside the app to start to play with CSS if we can
