### ISSUE TITLE
truncation of text in results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#241]
How can we eliminate the truncation of text in the results menu? Example : neighbourhood is truncated in the screen shot below 

![image](https://user-images.githubusercontent.com/59370537/80933063-0fe9a980-8d90-11ea-9dce-69aa71453c69.png)

**Comment by mullhol** [comment]
@Jiandong-Guo I think after looking at all the options, it will be best to make the text smaller.  Please implement this for all labels on all dashboard screens.

**Comment by Jiandong-Guo** [comment]
Holly confirmed that the requirement changed to shrink font. It's done

**Comment by T-T-Nguyen** [comment]
App name: Well-being Check
Short description:  A Pilot Study on Everyday Well-being conducted on the Well-being Check App (74)
Full description:  
Your participation is important
Statistics Canada is currently conducting a pilot study using the Well-being Check mobile app that asks Canadians in-the-moment questions about their activities and feelings. The goal is to gain a better understanding of the factors that influence well-being, particularly arts and culture activities, which are the main focus of this pilot. This initiative is in collaboration with Canada Council for the Arts and Canadian Heritage. The data will provide insight on the connections between activities and well-being, and could be used to develop programs that enhance people’s lives.
Keywords:
well-being,activity,arts and culture,statistics,ESMhappiness,emotions,Statistics Canada (97)

Support URL: www.statcan.gc.ca/wellbeing



App name: Bilan bien-être
Short description : Une étude pilote sur le bien-être quotidien menée avec l’appli Bilan bien-être (78)
Full description:
Votre participation est importante
Statistique Canada mène présentement une étude pilote effectuée à partir de l’application mobile Bilan bien-être qui pose des questions sur le vif aux Canadiens au sujet de leurs activités et de leurs sentiments. L’objectif est de mieux comprendre les facteurs qui influent sur le bien-être, en particulier les activités artistiques et culturelles, qui sont au cœur de cette étude pilote. Il s’agit d’une initiative menée en collaboration avec le Conseil des arts du Canada et Patrimoine canadien. Les données fourniront un éclairage sur les liens qui existent entre les activités et le bien-être et elles pourraient servir à élaborer des programmes qui améliorent la vie des gens. 
Keywords: bien-êtreactivité,arts et culture, statistiques,MEEbonheur,émotions,Statistique Canada
Support URL: www.statcan.gc.ca/bienetre
