### ISSUE TITLE
session expiry 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#242]
I received the session expiry notification within less than 2 minutes from using the app (just long enough to insert a ticket). This makes me assume it's triggering from when the respondent enters the app? It should trigger from the last action in the app.

**Comment by armonkolaei** [comment]
@mullhol can you please explain which screen this happened on.
1. was the app open before or was it the first start.
when app opens and you click home button the app is in freeze in background. was it in freeze state and you opened it?

**Comment by mullhol** [comment]
@armonkolaei As mentioned in this morning's meeting, it's happened to me on numerous screens.  Twice while in the questionnaire, and once when leaving the contact us menu and returning to the homepage (time out about 30 seconds after landing on homepage). 

It seems the timeout isn't resetting based on my use.  I would say I received the session expiry notification every 7 minutes, even though I was using the app consistently (about 45 minutes of testing, only stopping long enough to submit a ticket).

**Comment by armonkolaei** [comment]
session handler fixed and tested by @AJBouzidi & @mullhol
