### ISSUE TITLE
Notification content 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#245]
Notification content is not per content spec. 

**Regular notification should be:** 
How are you feeling right now? Sign in for a Well-being   Check!
Comment vous sentez-vous en ce moment? Connectez-vous pour obtenir un Bilan bien-être!

**Last attempt notification should be:** 
We haven’t heard from you in a while. Sign in for a Well-being Check!
Nous n’avons pas eu de vos   nouvelles depuis un certain temps. Connectez-vous pour obtenir un Bilan bien-être!

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 11th release, 
please reopen it if the functionality not working as expected.

**Comment by mullhol** [comment]
@AJBouzidi If this is still not working in Android, should this ticket actually be closed?
