### ISSUE TITLE
Confirm rate this app notification has been programmed 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#246]
Respondent should receive a notification to rate the app.  Respondent should receive this notification after they have completed 20 responses.  Has this been programmed? 

**Content for apple devices:** 
We love feedback! Tell us how we’re doing by rating us on the App Store.
Nous aimons votre rétroaction! Dites-nous ce que vous pensez de l’application en l’évaluant sur App Store.

**Content for android devices:** 
We love feedback! Tell us how we’re doing by rating us on Google Play Store.
Nous aimons votre rétroaction! Dites-nous ce que vous pensez de l’application en l’évaluant sur Google Play Store.

**Comment by Jiandong-Guo** [comment]
@AJBouzidi @mullhol 
Is it just  a popup message on app  after survey B or a regular local notification ?
What is the best time to send this notification if it is a notification ? 
 if send it immediately after survey B seems no difference to popup message

**Comment by mullhol** [comment]
@Jiandong-Guo I'm not certain on how rate this app messages are classified, that may be a better question for @armonkolaei.  They are generally light on text however, and link directly to the app store.  I've included the UX screen below for reference. 

Subject Matter wants it triggered after submission of the 20th survey.  I think it's fair to trigger it after the respondent presses submits the 20th instance, lands on the homepage, and their thank you toast has cleared the screen. 

![image](https://user-images.githubusercontent.com/59370537/81610542-b55fd700-93a7-11ea-8758-982f99c1967a.png)

**Comment by Jiandong-Guo** [comment]
Ok, that is a popup not notification.    after the respondent has done survey B 20 times and only on 20th time, The home page will popup this message instead of the regular black toast message.
if respondent click Rate Now, will open a browser to app store. if click Later, no nothing

**Comment by AJBouzidi** [comment]
This is has been fixed, please reopen it if the functionality not working as expected.
