### ISSUE TITLE
Confirm end of study content is programmed 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#247]
When the survey is no longer available, the respondent should receive the following message if they click on "start". Has this been programmed? 

The   Study on Everyday Well-being is now over. Thank you for participating! You can still access your personalized results.

L’Étude sur le bien-être au   quotidien est maintenant terminée. Nous vous remercions de votre   participation! Vous pouvez encore accéder à vos résultats personnalisés.

**Comment by AJBouzidi** [comment]
@mullhol How we will know when the survey is no longer available? 
we have specifics link or message on EQ saying this no more available?

**Comment by mullhol** [comment]
@AJBouzidi The EQ will no longer be able to be called.  When the respondent clicks start, they will see a page that basically says the survey has ended.

**Comment by Jiandong-Guo** [comment]
How about after 30days ?

**Comment by mullhol** [comment]
No, it's not after 30 days, it's when the survey is no longer available.  

After 30 days, the respondent will stop receiving notifications but can still complete well-being checks on their own schedule if they wish.  

Once the survey is no longer available however, they would need to receive the message in the ticket.

**Comment by Jiandong-Guo** [comment]
@AJBouzidi Since the EQ will display a message, seems  nothing is needed from App side
