### ISSUE TITLE
Lockdown the app library

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#250]

**Comment by AJBouzidi** [comment]
When we have a final list the libraray need to be locked to prevent breaking the project..

**Comment by zhuelle** [comment]
@Jiandong-Guo do you know how to do it?

**Comment by Jiandong-Guo** [comment]
I don't know how to lock the library, I think it is just don't add new package or update existing package, seems no way to lock it.

**Comment by zhuelle** [comment]
@AJBouzidi, @Jiandong-Guo found out that there is no way to lock the app library. Can you please help?

**Comment by Jiandong-Guo** [comment]
No more change on all packages and components since now, close it
