### ISSUE TITLE
Change of number of notifications not taking effect 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#251]
I had my notifications set to 3. 
I received one notification in the morning. I opened the app and revised my notification settings to 2. 
I received 2 more notifications in the afternoon/evening.  

I should have only received 1 notification after revising my settings, since I had already received a notification in the morning.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo I this case the number of Notifications received in the current day not been substracted from the notification number of the same day. 
if the user revise the number of Notifications then: Number of Notification(current day)= Number of Notifications - received Notifications.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 11th release, 
please reopen it if the functionality not working as expected.
