### ISSUE TITLE
Methodology testing - issue with distribution 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#252]
There is something going on with the second redistribution step. For example, if respondent goes to bed at 8pm and wakes up at 8am then the distribution should be as follows (from the methodology specs document):

![image](https://user-images.githubusercontent.com/59370537/81412202-84ff0b00-9111-11ea-8064-c50fb008c980.png)
![image](https://user-images.githubusercontent.com/59370537/81412243-947e5400-9111-11ea-896d-88cbcbed38bd.png)

but this is what appears in the simulator details (for a weekday):

We have to do Second time adjust for non primary interval, since some non primary probability > minimum of primary probability
Intervals after second adjust:
Date:Fri May 08 2020 08:00:00 GMT-0400 (Eastern Daylight Time) Hour:8 Percentage:4.00 IsPrimary:false
Date:Fri May 08 2020 09:00:00 GMT-0400 (Eastern Daylight Time) Hour:9 Percentage:4.00 IsPrimary:false
Date:Fri May 08 2020 10:00:00 GMT-0400 (Eastern Daylight Time) Hour:10 Percentage:6.03 IsPrimary:true
Date:Fri May 08 2020 11:00:00 GMT-0400 (Eastern Daylight Time) Hour:11 Percentage:7.54 IsPrimary:true
Date:Fri May 08 2020 12:00:00 GMT-0400 (Eastern Daylight Time) Hour:12 Percentage:7.54 IsPrimary:true
Date:Fri May 08 2020 13:00:00 GMT-0400 (Eastern Daylight Time) Hour:13 Percentage:7.54 IsPrimary:true
Date:Fri May 08 2020 14:00:00 GMT-0400 (Eastern Daylight Time) Hour:14 Percentage:7.54 IsPrimary:true
Date:Fri May 08 2020 15:00:00 GMT-0400 (Eastern Daylight Time) Hour:15 Percentage:7.54 IsPrimary:true
Date:Fri May 08 2020 16:00:00 GMT-0400 (Eastern Daylight Time) Hour:16 Percentage:6.03 IsPrimary:true
Date:Fri May 08 2020 17:00:00 GMT-0400 (Eastern Daylight Time) Hour:17 Percentage:7.54 IsPrimary:true
Date:Fri May 08 2020 18:00:00 GMT-0400 (Eastern Daylight Time) Hour:18 Percentage:15.08 IsPrimary:true
Date:Fri May 08 2020 19:00:00 GMT-0400 (Eastern Daylight Time) Hour:19 Percentage:19.61 IsPrimary:true

The sum of the percentages should always be 100 after all the re-distrubtions. I’d recommend including a validation step here to check. In this example, the sum of percentages is 107.53 when it should be 100%

**Comment by Jiandong-Guo** [comment]
@mullhol :The reason causing different percentage between the testing data and app detail result is that the testing may use wrong percentage for 10h-11h ,it should be 4 not 5. I checked the GSS29 data in the algorithm specs and it is 4 for example 1 and 2,  but the example 3 is using 5, and our app is using 4 from very beginning.   Also the total percentage is 100, 4.00+4.00+6.03+7.54+7.54+7.54+7.54+7.54+ 6.03+7.54+15.08+19.61=99.99(actually the behind is 4.0000000+4.0000000+6.0327869+7.5409836+7.5409836+7.5409836+7.5409836+7.54098361+6.03278689+7.54098361+15.08196721+19.60655738=100.000000) 
Please clarify the right percentage for 10h-11h for weekday.

**Comment by mullhol** [comment]
@Jiandong-Guo 
From Amanda: 
Just want to confirm that the percentage for the 10-11h should be 4%. Trisha was able to login and confirm this morning and she updated the pinging strategy document in GCDocs. That was a typo in example 3.

**Comment by Jiandong-Guo** [comment]
It is confirmed by Holly, It is 4% for 10-11H, so nothing is needed to change
