### ISSUE TITLE
Methodology testing - affected button

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#253]
I’m not sure if the affected button is working as expected. I tried an example of 5 notifications, an awake time of 6am and a sleep time of 11pm with a scheduling date time of 9am and the affected button selected but the respondent still received 5 notifications on the first day (instead of 4). I tried several different scenarios and all of them had 5 notifications on the first day even if the affected checkbox was selected. It only seemed to work as expected if I refreshed the simulator and started from scratch. Was this supposed to happen?

**Comment by AJBouzidi** [comment]
This is an example of testing. 
I got 4 Notifications first day and 5 Notifications the rest of 3 days.
![test](https://user-images.githubusercontent.com/58231743/81441322-93fcb200-913f-11ea-96bc-2fc75603ac65.PNG)

**Comment by AJBouzidi** [comment]
This is has been fixed and has been deployed in simulator 2.4, please reopen it if the functionality not working as expected.
