### ISSUE TITLE
Methodology Testing - please verify 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#254]
Question about how a “day” is defined: Is this based on the number of hours that a respondent is awake or the calendar day? For example, say respondent goes to bed at 2am and wakes up at 9am. If we’re talking about tomorrow, the possible intervals are: 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1.  So 15 of these intervals fall on the same calendar day and 2 fall on the next calendar day. I just want to verify how the app will handle this? Will they get 5 notifications on the first day or could it include the ones that overlap into the next calendar day? The specs were set up for the second scenario and this appears to be working for the examples I tested, but just want to make sure that is how the programmer understood it.

**Comment by Jiandong-Guo** [comment]
it was addressed in the simulator and the algorithm will figure out the "new day" especially for night shift
