### ISSUE TITLE
Italics required in Getting Started

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#258]
Names of acts  need to be italicized in the getting started content (ISR).  I've marked them in red in the attached document.  

This change affects getting started both in entry, and in info menu. 

[Italics getting started.docx](https://github.com/StatCan/WellbeingCheckUAT/files/4610676/Italics.getting.started.docx)

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 18th release, please reopen it if the functionality not working as expected.
