### ISSUE TITLE
Italics required in T&C 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#259]
Names of acts and standards need to be italicized in terms and conditions.  I've marked them in red in the attached document.  

This change affects T&C both in entry, and in settings menu. 

[Italics terms and conditions.docx](https://github.com/StatCan/WellbeingCheckUAT/files/4610648/Italics.terms.and.conditions.docx)

**Comment by AJBouzidi** [comment]
@mullhol This is has been fixed and will be in the may 18th release, please reopen it if the functionality not working as expected.
