### ISSUE TITLE
Notifications toggle in settings menu doesn't reflect change in ios settings 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#260]
- I downloaded a new version of the app and declined notifications.  
- I went through the process of creating my password, landed on the home page, and clicked on settings. 
- I toggled to turn settings on.  
- I received the question of visiting the device settings. 
- I went to device settings to turn notifications on. 
- When I returned to the app, the toggle was still off.  

Is there a way to switch the toggle to ON when the user returns to the app, rather than make them go through the ios settings and still have to toggle in the app?

**Comment by AJBouzidi** [comment]
Hi @armonkolaei could you please look into this one if you have time.

**Comment by armonkolaei** [comment]
As discussed over the phone. The OS notification and the application notification are separate.
From the application side, we request from the operating system Permission to send notification.

So if the user has turned the OS notification off we can redirect them to that page to turn it back on and grant us permission from the OS side. when they come back we cannot guarantee if they did what they intended and there are no hooks from the OS. so on the app side we cannot automatically assume we have permission now and ask again every time the app comes from for-ground. This is normal behaviour and users should be familiar with this flow.
