### ISSUE TITLE
hyperlinks in T&C 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#261]
There are links in the T&C which need to be formatted as hyperlinks.  Links requiring attention are in the following sections: 

1) General terms and conditions
2) Privacy notice
3) Official language notice 
4) Accessibility notice 
5) Trademark notice

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 18th release, 
please reopen it if the functionality not working as expected.
