### ISSUE TITLE
Issue with accessing content in results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#263]
At times, the content does not appear in the results menu, only the heading. If I return to the homepage and then go back to the results menu, the content is visible on the second attempt.  Joelle has encountered the same issue.

**Comment by Jiandong-Guo** [comment]
add function:
     disable result button in home page after survey B done until all the slow fetching graph actions done

**Comment by Jiandong-Guo** [comment]
According Holly's suggestion, instead of disabling button, just display loading icon to wait for back-end fetching graph action done.

**Comment by Jiandong-Guo** [comment]
it was fixed and ready for test
