### ISSUE TITLE
QDRC is recommending:Immediate validation on password field 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#264]
QDRC is recommending the following for the secure account screen: 
When the user enters their password in the first password field, the field verifies immediately if the respondent has entered their password to meet requirements.  This would prevent the respondent from entering the same password in the second field, then being told it does not meet requirements.  Is it possible to turn the outline of the first password field green if the password meets requirements, or red if it does not? 

Or, to display a checkmark if the password meets requirements, and exclamation if it does not?

**Comment by AJBouzidi** [comment]
@armonkolaei validation in the textinput instead validation after the create button been clicked.

**Comment by armonkolaei** [comment]
added real time password validator on input change for register and forgot password
