### ISSUE TITLE
Placement of logo on login screen 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#268]
Please center app logo between password box and top of screen.  Also, match app name font with font from splash page (bolder font) 

![image](https://user-images.githubusercontent.com/59370537/81938425-e405c980-95c2-11ea-8fae-ae2bab58eb35.png)

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 1st release, please reopen it if the functionality not working as expected.
