### ISSUE TITLE
Revision to do not disturb 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#269]
The QDRC report suggests the following for the settings menu: 

![image](https://user-images.githubusercontent.com/59370537/81846069-879d9e00-951f-11ea-9ef8-8dbefc5deade.png)

Please revise the do not disturb section to reflect this. The words before and after are to be bolded as follows:
Do not disturb **before**: 
Ne pas déranger **avant**
Do not disturb **after**: 
Ne pas déranger **après**

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 18th release, please reopen it if the functionality not working as expected.
