### ISSUE TITLE
Notifications received when settings toggle off 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#271]
I downloaded a fresh version of the app and declined notifications on entry. 
I went to the settings menu and toggled notifications on. 
I was asked if I wanted to go to ios settings to turn on.  I said yes. 
I turned on notifications for the app in ios settings.
I returned to the app settings menu, where the toggle was still off.  I left the toggle off. 

I received two notifications in the afternoon/evening.

**Comment by Jiandong-Guo** [comment]
This is has been fixed and will be in the may 18th release,
please reopen it if the functionality not working as expected.
