### ISSUE TITLE
Duplicate notifications 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#272]
Joelle received two notifications at the same time yesterday (5pm)

**Comment by Jiandong-Guo** [comment]
after check code,there is no way to get duplicated schedule from the algorithm, after search online, got the result said that it might happen if schedule notification for passed time.  even if the chance is very slim for our algorithm, just add extra 5 minutes for current time to make sure all the algorithm calculation be done within the 5 minutes before setup notification.  the change was pushed to master for test and see the result.
