### ISSUE TITLE
Last chance notification 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#273]
I received the last chance notification after not reporting for 4 days, which is good.  However, I received it while I had notifications off, which is not good.  Respondents should not be eligible for any notifications if their notifications are turned off.

**Comment by Jiandong-Guo** [comment]
This is the same issue as #271, it was caused by arranging schedules after survey B done process which missing a condition determination of  notifications on/off. it was fixed and for test.
