### ISSUE TITLE
Revise font format in Contact menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#277]
The look and feel of the info and contact us menu needs to be the same format. Please revise Contact us to:

Remove colons at end of headings (in English and French versions)
Resize headings and bold font
Confirm body font is the same size as info menu - if not, revise size to match info menu
Revise body font colour to match info menu 

![image](https://user-images.githubusercontent.com/59370537/82565902-28581300-9b49-11ea-851a-d52e1dee8179.png)

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 25th release, please reopen it if the functionality not working as expected.
