### ISSUE TITLE
Time picker bouncing 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#279]
I tried to set my do not disturb after time to 9:45.  After landing on 45, the picker bounced to 04. After a second attempt, it bounced to 50. I set it to 9:38 on third attempt and it stayed as selected. Will post video in Slack. 

Same issue encountered with do not disturb before time picker.

**Comment by AJBouzidi** [comment]
@mullhol please check this.

**Comment by mullhol** [comment]
@AJBouzidi  I am still having this issue.

**Comment by mullhol** [comment]
This seems to be working, will reopen if encountered again

**Comment by mullhol** [comment]
This is still happening, but not as often. Can we investigate this once more? 
iphone 11, ios 13.6

**Comment by Jiandong-Guo** [comment]
It is always disabled for simulator

**Comment by mullhol** [comment]
Still bouncing.

**Comment by AJBouzidi** [comment]
@mullhol : 2 timers has been deployed for testing. 

- first one in the Do not disturb before
- second one in the Do not disturb after
we will choose after the testing.

**Comment by mullhol** [comment]
Both of the new time pickers bounce as well, and more than the native version. At this stage, let's revert back to the native iOS version and we will accept the minor bouncing issue for the pilot.

**Comment by mullhol** [comment]
Confirmed original time picker has been returned to iOS.  We will accept as-is. Bouncing is minimal.
