### ISSUE TITLE
Body text in info menu and contact us menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#281]
Sorry to be a pain, but the body text in the info menu and contact us menu should be in black (all font currently formatted in grey).  We use black throughout the app in other menus and on the EQ, so the grey breaks the consistency.  

Once this change has been made I will stop asking for formatting changes to these menus :)

**Comment by AJBouzidi** [comment]
@mullhol what about T&C and Getting Started?

**Comment by mullhol** [comment]
@AJBouzidi Yes, same thing.  I assumed they were being pulled from the same source.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 1st release, please reopen it if the functionality not working as expected.
