### ISSUE TITLE
Results menu frozen 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#285]
I was able to enter the results menu on my first attempt, but was not able to scroll off the overview page to see the breakdowns.  I pressed return to go back to the homepage.  I tried entering the results menu again, but was unable to.  I crashed the app and logged in again.  I was still unable to access the results menu.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 8th release, please reopen it if the functionality not working as expected.
