### ISSUE TITLE
Information Menu frozen 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#287]
I entered the Info menu.  I expanded one section of the FAQ. I was not able to collapse it, or expand another section. I was not able to scroll through the rest of the menu.  I pressed return to go to the homepage.  After landing on the homepage I was unable to return to info menu.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 8th release, please reopen it if the functionality not working as expected.
