### ISSUE TITLE
Settings menu - Return button 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#288]
After updating my app, I logged in and went directly to the settings menu to confirm my settings were still correct.  They were, so I did not make any changes.  I pressed return to go back to the home screen, but the return button was disabled.  I had to crash the app and log in again.  This happened each time I visited the settings menu.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 8th release, please reopen it if the functionality not working as expected.
