### ISSUE TITLE
Revision in Getting Started/Info menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#289]
Remove question mark from "Why we are conducting this study?".  It should simply be "Why we are conducting this study"

Remove question mark from French version as well - "Pourquoi nous menons cette étude?".  It should be "Pourquoi nous menons cette étude"

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 8th release, please reopen it if the functionality not working as expected
