### ISSUE TITLE
Time out 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#296]
Time out function worked on settings menu when first tested. 
It also worked on Info and Contact Us menus when first tested. 

When testing the Results menu, the time out message was not received, the app went directly to the login page. 

When testing the homepage, nothing happened - it stayed on the homepage and allowed me to continue navigating the app.  

Tested a second time on Settings menu, and it did not work.  I set timers for 16 minutes for each test.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 15th release, please reopen it if the functionality not working as expected.

**Comment by Jiandong-Guo** [comment]
@AJBouzidi @mullhol : 1)I tested the time out again on andriod phone, it won't pop up message as Ellen reported at least for some of andriod devices.  the reason I think is the app will put into sleep(inactive state) after couple of minutes, and the timer will stop if the lock screen function was set on the device.  this issue never happen on simulator and even on device used as a simulator, but it does happen on standalone device.  so it will bring out another question, will the timer will need to continue to tick when the app turns into sleep state ?

**Comment by Jiandong-Guo** [comment]
A simple example is you open the app to home screen(the app is on foreground), then you switch to phone app to make a phone call or go to calculator app to do some math(our app will turn into background or inactive), then you switch back our app(turn into active again). do we need to ask the password immediately?

**Comment by mullhol** [comment]
_will the timer will need to continue to tick when the app turns into sleep state ?_ - Yes it will.  We can't guarantee when the phone comes out of sleep state, that it is the original user who has unlocked the phone.  Our job is to protect the data in the app, and the only thing that will do that in this instance is for the time out function to work in all cases.  

_A simple example is you open the app to home screen(the app is on foreground), then you switch to phone app to make a phone call or go to calculator app to do some math(our app will turn into background or inactive), then you switch back our app(turn into active again)._ - This example isn't where Ellen is having the issue.  Her issue is if she opens the app, then walks away from her phone, the phone will lock and prevent the timeout function from operating. This does not happen on Apple, seems specific to Android.  

do we need to ask the password immediately? - We should only be asking for the password if the timeout window has closed.  If the respondent just needs to check something quickly in another app before returning to ours, it will discourage them from using it if they have to enter the password again immediately.  We know our password is long and was an issue in QDRC testing, so we should not have them re-enter the password unless the timeout window has closed or they have fully closed the app and are opening it to report.

**Comment by Jiandong-Guo** [comment]
So, should the timer be stopped during the period when our app turns into inactive ?

**Comment by Jiandong-Guo** [comment]
oh, you answered it already

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 29th release, please reopen it if the functionality not working as expected.

**Comment by mullhol** [comment]
All updates have been implemented successfully.
