### ISSUE TITLE
Methodology Testing - First interval 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#297]
-	If a user enters an awake time of X:00 (i.e., 6:00 am), please ensure that the first interval available for selection is X:00 to X:59 (i.e,. 6:00 am to 6:59am). Currently, if a user says they wake up at 6:00am then the “awake hour round up” is set to 6am (which is correct) but the first interval available for selection is actually 7-8 am. If the respondent wakes up at 6:01 then we don’t want the notifications occurring before 7am but if they wake up at 6:00 precisely on the hour, they can receive a notification in this interval. It’s a minor detail but it does impact the probabilities. 
-	Note that this is not an issue for sleep time (if the respondent enters a sleep time of 10pm then the last interval to receive a notification is 9-10pm, which is what we want).

**Comment by Jiandong-Guo** [comment]
I double checked the notification code, the logic is right.  that is if the user enter awake time x:00(i.e.,6:00),the first interval will start from x:00-x:59(i.e.,6:00-6:59),  but weather or not it is included in the list also depends on the current time, if current time passed the interval starting time, it will be excluded from the list.i.e., current time is 6:15am,  you will see the first interval is 7-8 am.

**Comment by mullhol** [comment]
@Jiandong-Guo Amanda has taken another look based on your feedback but has provided the following example.  Can you revisit? 

It looks like the scheduling date and time was part of my problem. However, it does seem that first interval is still off by one hour in some situations. 

Here is an example where I expected the first available interval to be 7am-8am but the simulator is showing 8am-9am:

	Ping Num: 2
	Awake Time: 6:00 AM
	Sleep Time: 11:45PM
	Scheduling DateTime: 6:01 AM 
The final Intervals number:15
Date:Wed Jun 17 2020 08:00:00 GMT-0400 (Eastern Daylight Time) Hour: 8 Percentage: 0 IsPrimary: false
Date:Wed Jun 17 2020 09:00:00 GMT-0400 (Eastern Daylight Time) Hour: 9 Percentage: 0 IsPrimary: false
Date:Wed Jun 17 2020 10:00:00 GMT-0400 (Eastern Daylight Time) Hour: 10 Percentage: 4 IsPrimary: true
Date:Wed Jun 17 2020 11:00:00 GMT-0400 (Eastern Daylight Time) Hour: 11 Percentage: 5 IsPrimary: true
Date:Wed Jun 17 2020 12:00:00 GMT-0400 (Eastern Daylight Time) Hour: 12 Percentage: 5 IsPrimary: true
Date:Wed Jun 17 2020 13:00:00 GMT-0400 (Eastern Daylight Time) Hour: 13 Percentage: 5 IsPrimary: true
Date:Wed Jun 17 2020 14:00:00 GMT-0400 (Eastern Daylight Time) Hour: 14 Percentage: 5 IsPrimary: true
Date:Wed Jun 17 2020 15:00:00 GMT-0400 (Eastern Daylight Time) Hour: 15 Percentage: 5 IsPrimary: true
Date:Wed Jun 17 2020 16:00:00 GMT-0400 (Eastern Daylight Time) Hour: 16 Percentage: 4 IsPrimary: true
Date:Wed Jun 17 2020 17:00:00 GMT-0400 (Eastern Daylight Time) Hour: 17 Percentage: 5 IsPrimary: true
Date:Wed Jun 17 2020 18:00:00 GMT-0400 (Eastern Daylight Time) Hour: 18 Percentage: 10 IsPrimary: true
Date:Wed Jun 17 2020 19:00:00 GMT-0400 (Eastern Daylight Time) Hour: 19 Percentage: 13 IsPrimary: true
Date:Wed Jun 17 2020 20:00:00 GMT-0400 (Eastern Daylight Time) Hour: 20 Percentage: 15 IsPrimary: true
Date:Wed Jun 17 2020 21:00:00 GMT-0400 (Eastern Daylight Time) Hour: 21 Percentage: 12 IsPrimary: true
Date:Wed Jun 17 2020 22:00:00 GMT-0400 (Eastern Daylight Time) Hour: 22 Percentage: 6 IsPrimary: true

**Comment by Jiandong-Guo** [comment]
@mullhol :For the example above, the algorithm is:  awake hour=6:00, sleep hour=...,  current time=6:01,  and I think it is after survey A done.  one of  our rule is notification starts to send one hour after survey A done, so the available start time becomes 7:01, and also it passes the start point of interval 7:00-8:00, so the final available interval becomes to 8:00-9:00.   Please let me know if any logic need to be changed.

**Comment by mullhol** [comment]
Amanda confirms this ticket can be closed: 
" I tested to make sure that there is only the 1 hour delay when a user does QA+B and not for any settings change. So that is good and programmed correctly. "
