### ISSUE TITLE
Boundary of start button

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#298]
If I tap the homepage north east, south east, north west, or south west of the start button, it registers as if I've tapped the start button and opens the EQ. 

If I tap the homepage north, south, east, or west of the start button, nothing happens.  This is the expected behaviour.  

We need to correct the boundaries in the first example so an EQ is not called.  The respondent could easily tap slightly too low for the settings menu, or slightly too high for the info/results menus and end up calling an EQ.  Will add video in slack.

**Comment by Jiandong-Guo** [comment]
fixed

**Comment by mullhol** [comment]
This has been successfully implemented
