### ISSUE TITLE
Methodology Request - Improvements to simulator 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#299]
Methodology would like to know if the following revisions would be possible to the simulator...

-	Make the number of notifications a drop down list so that the only options are 2, 3, 4 and 5 (similar to the app).
-	Add a verification step on the details screen to make sure that the sum of the distribution (i.e., “percentages”) is 100%.
-	Don’t allow the simulator to run if the parameters are set up for an awake interval of less than 3 hours (similar to the app). Ideally the same message would occur in the simulator that the user would see in the app.

**Comment by Jiandong-Guo** [comment]
Done
