### ISSUE TITLE
Revise homepage message 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#300]
Please revise the message respondents receive the first time they see the homepage to: 

Customize the number of notifications and the window of time you receive them in the Settings menu. (add icon of settings wheel if possible - not functional, display only)

Personnalisez le nombre de notifications et l’intervalle de temps  durant lequel vous les recevrez dans le menu des Paramètres. (add icon of settings wheel if possible - not functional, display only)

![image](https://user-images.githubusercontent.com/59370537/84274273-aa5eaa80-aafd-11ea-8fc8-e827cdf162c9.png)

**Comment by mullhol** [comment]
@AJBouzidi 

Please include a period at the end of each as well.... edited content in original ticket body to include. 

![image](https://user-images.githubusercontent.com/59370537/84391587-2e309980-abc7-11ea-8ebd-9812c44fd9c7.png)

**Comment by AJBouzidi** [comment]
fixed

**Comment by mullhol** [comment]
This has been implemented

![image](https://user-images.githubusercontent.com/59370537/84661938-11f36c00-aee9-11ea-9615-b630df656358.png)
