### ISSUE TITLE
Revise order of overview graph in Results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#302]
Overview graph is currently ordered to display: 
happy
relaxed
anxious
awake
in control

Please revise this order as follows to align with the questionnaire (revised labels from ticket 159 in brackets): 
happy (Happy - Heureux(se))
relaxed (Relaxed - Détendu(e))
focused (Focused - Concentré(e))
in control (In control of your emotions - En contrôle de vos émotions)
anxious (Anxious - Anxieux(se))

**Comment by Jiandong-Guo** [comment]
done

**Comment by mullhol** [comment]
This has not been implemented.

**Comment by mullhol** [comment]
After downloading a fresh version of the app, I can see this has been successfully implemented.  It did not appear after updating the app however.  This is a different issue.  

cc @AJBouzidi
