### ISSUE TITLE
Revision to sentiment labels in Results menu

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#303]
Please revise the sentiment labels in the results menu to the following: 

Happy
Heureux(se)

Relaxed
Détendu(e)

Anxious
Anxieux(se)

Focused
Concentré(e)

In control of your emotions
En contrôle de vos émotions

This revision affects all graphs. 
![image](https://user-images.githubusercontent.com/59370537/84394929-908b9900-abcb-11ea-8daf-06c3b8bc4e2c.png)

![image](https://user-images.githubusercontent.com/59370537/84394973-9e411e80-abcb-11ea-82d4-9502b625e021.png)

**Comment by Jiandong-Guo** [comment]
Done

**Comment by mullhol** [comment]
This has not been implemented.  There are errors on all screens in both languages, including both French and English in the French version of the "with others" screen.  Please correct all screens per the original ticket. 

![image](https://user-images.githubusercontent.com/59370537/84660796-5f6ed980-aee7-11ea-9147-c80ec48bc7a8.png)

![image](https://user-images.githubusercontent.com/59370537/84660822-6c8bc880-aee7-11ea-8226-109dcef79fa0.png)

![image](https://user-images.githubusercontent.com/59370537/84660867-7dd4d500-aee7-11ea-9d1d-fafcff835e27.png)

**Comment by mullhol** [comment]
After downloading a fresh version of the app, I can see this has been successfully implemented. It did not appear after updating the app however. This is a different issue.

cc @AJBouzidi
