### ISSUE TITLE
Revision to y axis label in results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#304]
Please revise the label on the y axis from average score to:

Average rating
Évaluation moyenne

This revision affects the location graph, the activity graph, and the others graph

**Comment by Jiandong-Guo** [comment]
done

**Comment by mullhol** [comment]
This has not been implemented.  App still says Average score and Score moyen.

**Comment by mullhol** [comment]
After downloading a fresh version of the app, I can see this has been successfully implemented. It did not appear after updating the app however. This is a different issue.

cc @AJBouzidi
