### ISSUE TITLE
Titles for graphs in results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#305]
Here are the COMM-approved titles for each graph in the results menu...

Please replace "your feelings" title with: 
Your feelings: a snapshot
Aperçu de vos sentiments

Please replace "how you are feeling by location" title with: 
Your feelings: by location
Vos sentiments selon l’emplacement

Please replace "how you are feeling by activity" title with: 
Your feelings: by activity
Vos sentiments selon l’activité

Please replace "how you are feeling with others" title with: 
Your feelings: alone or with others
Vos sentiments : seul ou avec d’autres

**Comment by Jiandong-Guo** [comment]
Done

**Comment by mullhol** [comment]
Confirmed implemented.
