### ISSUE TITLE
API: Web API to collect paradata from mobile to CMP 

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#31]

**Comment by AJBouzidi** [comment]
@Jiandong-Guo , @saqib-dareshani,  Hi, will you please let me know the status of this.
I Know we define the contract and how we will pass the information to the Web API. @saqib-dareshani did you have the connection to WebAPI already.

**Comment by saqib-dareshani** [comment]
Hello Ali,

I don’t have the API yet.  As soon as I have it I can start integrating.

Cheers,
Saqib

**Comment by AJBouzidi** [comment]
@Jiandong-Guo, @saqib-dareshani  WebAPI should be in the cloud already. i'll give access to it. 
@Jiandong-Guo already setup his part receiving the paradata In the webAPi

**Comment by Jiandong-Guo** [comment]
It was implemented already
