### ISSUE TITLE
Spinning wheel on homepage after questionnaire submission 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#311]
After I complete a questionnaire submission and return to the homepage, both the spinning wheel and  the thank you toast are visible on the homepage.  The respondent should not see the wheel at this point.  

The wheel should show: 
1) When the respondent is waiting for the questionnaire to load
2) When the respondent is waiting for the questionnaire to submit, before returning to the homepage (if possible)
3) When the respondent is accessing the results menu, if results have not loaded yet. 

video in slack to support this ticket.

**Comment by Jiandong-Guo** [comment]
fixed
