### ISSUE TITLE
Refresh Results menu when updating app 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#312]
Currently the results menu does not refresh when the respondent updates the app, only after they complete another questionnaire B submission.  If possible, the results menu should refresh when the app version is updated in case we have had to make revisions to this menu.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo At launch time compare the previous app version and the current app version and if they are diffrent then update the graph list.

**Comment by Jiandong-Guo** [comment]
@AJBouzidi:  Changing app version won't affect graph, they are affected only by WebApi version which is independent to app version.   even you go retrieve graphs every time you upgrade app, the graphs are still same.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo 
this is the scenario we try to avoid: 

1. we update the WebAPI (dashboard) 
2. user update the application to new version
3. user does not complete any EQ questionnaire 
4. user goes to see the dashboard 
in this case does the user sees the update in the dashboard.

**Comment by Jiandong-Guo** [comment]
Added upgrade checking in app

**Comment by mullhol** [comment]
This wasn’t included in the release note for the new version, and the results menu didn’t refresh after updating my app this morning. I assume this work is still to be done.

**Comment by mullhol** [comment]
@Jiandong-Guo Can you confirm if this work is complete?

**Comment by mullhol** [comment]
Successfully implemented
