### ISSUE TITLE
Subject Matter Testing - duplicate notifications

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#313]
Joelle received duplicated notifications at 10:23 on June 14. She has experienced this issue on almost all app releases to date. 

![image](https://user-images.githubusercontent.com/59370537/84671409-597ff500-aef5-11ea-812b-f9686255801a.png)

**Comment by AJBouzidi** [comment]
@Jiandong-Guo please add your finding about this issues here.

**Comment by mullhol** [comment]
Joelle is still monitoring for additional duplicate notifications.  This ticket will remain on hold for the time being.

**Comment by mullhol** [comment]
This has not been reported again, will reopen if required.

**Comment by mullhol** [comment]
Rachel is now experiencing this issue.  She has a Google Pixel 3 running on Android 10. Her notes: 

There was aa time when I was testing this issue that I was sent 3 notifications at the same time. When it happened with me I had gotten two notifications already that day (~12pm, 5pm), went to change notifications to three shortly after the second, and at about 7pm received three pings. When I saw them, they were all stacked and all said they occurred 6 minutes ago.

**Comment by mullhol** [comment]
Rachel is still encountering this issue with the current version of the app.  Her comment - "it was just the same notification twice, they were stacked, said the same text (How are you feeling right now? Sign in for a Well-being Check!) and were both timed at being received 18 minutes before I saw them"

Joelle also received 3 at the same time this morning. 

CC @AJBouzidi @Jiandong-Guo

**Comment by Jiandong-Guo** [comment]
https://github.com/expo/expo/issues/3946

**Comment by mullhol** [comment]
This has not been an issue for Ellen, Holly, or Trish.  Closing the ticket for the time being and will open a new ticket if SM continues to have an issue.
