### ISSUE TITLE
Revise timeout time

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#315]
After testing this for weeks, I can say 15 minutes is a long time.  Please revise the timeout period to 7 minutes.  This will give the respondent more than enough time to complete a questionnaire submission and will be closer to the requirement other secure apps (ie banking apps) have implemented.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 22th release, please reopen it if the functionality not working as expected.
