### ISSUE TITLE
Plus and minus signs in results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#317]
Per QDRC's recommendation, please add plus and minus signs to each line in the results overview graph to visualize positive and negative levels for the respondent. 

Per my rather rudimentary graphic skills below, happy, relaxed, focused, and in control of your emotions should have minus signs on the 0 end of the scale and plus signs on the 10 end of the scale. 

The anxiety bar should have a plus on the 0 end of the scale, and a minus sign on the 10 end of the scale. 

![image](https://user-images.githubusercontent.com/59370537/84919044-6afd0480-b08f-11ea-83c4-892e3531fc80.png)

**Comment by Jiandong-Guo** [comment]
The minimum number is 0,

**Comment by mullhol** [comment]
@Jiandong-Guo We're not signalling a negative number, but the less positive end of the spectrum (analytically).  

All questions rate sentiments as 0 being "not very" and 10 being "very".  But the interpretation of the result would be very different based on which sentiment you are analyzing. For example - if I regularly report between 0-3 to say I'm not feeling very anxious, this is good!  If I consistently report 0-3 for not very happy however, this is not good.  

If I consistently report 9-10 to say I'm feeling very anxious, this is not good.  But if I consistently report 9-10 to say I'm feeling very happy, this is good.  

QDRC feels adding a positive and negative sign to the graphs will help the respondent quickly understand if they are feeling good, or not so good by knowing which end of the scale is the "good side" and which is the "not good" side.

**Comment by AJBouzidi** [comment]
@mullhol @Jiandong-Guo We hope that the people will not try to click on the +- sign thinking they can change their score.

**Comment by mullhol** [comment]
Confirmed implemented.
