### ISSUE TITLE
Revisions to results - seul ou avec d'autres screen 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#319]
Please revise heading to : Vos sentiments : seul(e) ou avec d'autres

Please revise x axis categories for friends and alone to: 
Avec des ami(e)s
Seul(e)

**Comment by AJBouzidi** [comment]
@mullhol do you keep "Tout seul(e)" or "Seul(e)"

**Comment by mullhol** [comment]
@AJBouzidi it needs to change to just "Seul(e)".

**Comment by Jiandong-Guo** [comment]
Fixed
