### ISSUE TITLE
App opened in wrong language 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#320]
I updated my app version this morning. The first time I opened it, it opened in French.  

Rather than signing in, I crashed the app and opened it again.  It again opened in French.  I toggled to English and crashed the app again.  When I opened it the third time, it opened in English.  

It should not have opened in French to begin with however, I had not revised my settings to French before updating the app, and my OS is English.

**Comment by AJBouzidi** [comment]
@mullhol @Jiandong-Guo 

- After investigation trying to reproduce the issue and here what maybe the cause of settings not saved:

After any changes done on the settings screen and the user dismiss the application without clicking on the "RETURN" Button, in this case any changes will not be saved. in the current solution all changes will be validated and saved when the user hit the "RETURN" button. 

- Potential solution: move the saving and validation on the settings screen. Any changes to Number of Notifications, to Do not disturb before and after and to the language will be validated and saved before the user hits the "RETURN" button. 

- The validation of the 3 minimum hours will be validated when the user click confirm button on the timer picker.  this my need to be tested to see if this solution will create any possible burden to the user.

**Comment by mullhol** [comment]
This is the ticket that made us realize we need to change the behaviour of the settings menu so we’re not reliant on the return button.  Once that work has been implemented, I will test and expect to be able to close this.

**Comment by mullhol** [comment]
This issue has been resolved
