### ISSUE TITLE
Email needed for the app communication

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#321]

**Comment by mullhol** [comment]
From Ali: 
For the “Email needed issue” it’s E-mail group that will be used for the stores feedback.
Now every comments/questions will be sent to infostat@canada.ca App related or Survey related. 
We need this group that will receive the request from infostat@canada.ca after triages.

**Comment by mullhol** [comment]
This ticket will be parked for a few weeks.  I will investigate the proper email to be used and process to be followed.

**Comment by mullhol** [comment]
This has been provided to Sylvie Bonhomme to investigate and determine a decision.

**Comment by Jiandong-Guo** [comment]
Close according to Trish's email
