### ISSUE TITLE
Release notes for app update

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#322]
French and English version in beta testing note when the app updated

**Comment by mullhol** [comment]
from Ali: for the release note when the app will be in prod . If there is an update we need to specify what has changed.
I think the update release note should come mainly from the business side in both languages.

**Comment by mullhol** [comment]
This is a procedure which will be implemented in production.  CPRD will be responsible for coordinating development and translation of release notes with COMM.  This ticket can be closed as it is not an issue affecting the testing environment/app function.

**Comment by T-T-Nguyen** [comment]
Should there be a new release in the future, notes will be added.
To be discussed after Collection

**Comment by T-T-Nguyen** [comment]
@zhuelle 

**iOS**
Initial Version
Known limitation: This version of Vitali-T-Stat application is only compatible using light mode.

Première Version
Limitation connue : Cette version de l'application Vitali-T-Stat fonctionne uniquement en mode apparence claire.

**Comment by Jiandong-Guo** [comment]
It is not allowed to change now, because it is passed the review, if really want to change, we have to cancel the current release and create a new release to review even it is not publicly facing yet.

**Comment by zhuelle** [comment]
@T-T-Nguyen not sure if you have seen Jiandong's comments above. Please advise

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo 
Note: This will not be applied for this release.
Please place on hold*
