### ISSUE TITLE
update the rate the applications link

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#326]

**Comment by zhuelle** [comment]
@AJBouzidi Please provide some details about this request as it is not clear to me on what need to be done.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo @zhuelle:
Android:
Linking.OpenURL("http://play.google.com/store/apps/details?id=" + Application.bundleIdentifier);
iOS: 
Linking.OpenURL( "https://apps.apple.com/app/idXXXXXXXXXX?action=write-review")

done and checked to master

**Comment by mullhol** [comment]
@AJBouzidi I'm assuming this can only be tested once we're in prod, but let me know if that assumption is wrong...

**Comment by mullhol** [comment]
This can only be tested in production once the app has been deployed to app store.

**Comment by mullhol** [comment]
@zhuelle @t-t-nguyen

This ticket concerns the links in the "rate this application" request.  After 20 questionnaire responses, the respondent will receive a notification asking if they would like to rate the application.  If they select yes, they will flow to the app store where they would provide a rating and any comments.  

The function of flowing to the app store needs to be tested.
