### ISSUE TITLE
Fetch graphs synchronously to avoid overwhelming servrers

### ISSUE THREAD

**Issue by thierryrama** [StatCan/wellBeingCheck#338]
Don't mark the fetchImage as async to allow for sequential download of the graphs. https://github.com/StatCan/wellBeingCheck/blob/2f60eaf09290f8f524986ac46e422005ca7d5ac0/wellBeingCheck/src/utils/fetchJwToken.tsx#L120

**Comment by Jiandong-Guo** [comment]
Removed, will see the result in next release

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo When is the next release?

**Comment by thierryrama** [comment]
@Jiandong-Guo , I am not sure which repository the you build the mobileapp from but I do not see the commit where you removed the async from the fetchImage.

**Comment by Jiandong-Guo** [comment]
Not commit to the github yet,

**Comment by thierryrama** [comment]
Another option to reduce the number of concurrent connections is to fetch both En, and Fr graphs in `fetchImage` so that would make it 4 concurrent connections instead of 8.
For now, it is even OK to not modify anything as after analysis, the issue with has to do with how the ICOS QA is tuned so even 8 concurrent connections should be fine.

**Comment by Jiandong-Guo** [comment]
the async key word was removed from this function.
