### ISSUE TITLE
EQ: Questionnaire screen presentation

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#58]
If you scroll on one question to answer and select "next", the subsequent screen presents aligned with the bottom of the screen rather than the top.  All new screens need to align top.

**Comment by AJBouzidi** [comment]
This is working for certain IOS but Not for all of them. 
need to be validated.

**Comment by AJBouzidi** [comment]
@mullhol this issue still open.

**Comment by Jiandong-Guo** [comment]
It was fixed

**Comment by mullhol** [comment]
This issue is not resolved.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 8th release, please reopen it if the functionality not working as expected.

**Comment by mullhol** [comment]
This seems to be working consistently over the last few updates.  Ticket no longer required.
