### ISSUE TITLE
Login-Password Validation

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#62]
RegEx | Description
-- | --
^ | The password string will start this way
(?=.*[a-z])  | The string must contain at least 1 lowercase alphabetical character
(?=.*[A-Z]) | The string must contain at least 1 uppercase alphabetical character
(?=.*[0-9]) | The string must contain at least 1 numeric character
(?=.*[!@#$%^&*]) | The string must contain at least one special character, but we are escaping reserved RegEx characters to avoid conflict
(?=.{8,}) | The string must be eight characters or longer

Example: var strongRegex = new RegExp("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})");

Specification UX (page 34 ):
https://xd.adobe.com/view/17b2c6fa-f198-4235-a6b8-c009f13f2a7c-42e1/

**Comment by armonkolaei** [comment]
@AJBouzidi all validations are complete
