### ISSUE TITLE
API: Secured WebAPI 

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#63]
-Secure the connection between WBC Mobile Application and WebAPI
-Secure the connection between the WebAPI and Collection Management Portal (CMP)

-

**Comment by thierryrama** [comment]
All the required interfaces with the back-end apis are provided in ``src/api/back-end.servicets/BackEndService`` class.

Examples of calls can be seen in integration tests ``src/api/back-end.service.spec.ts``.
The jest tests are not running on the mobile devices but rather on Node.js so it has a different environment than react-native. Nonetheless, the difference that matters lies in the ``fetchApi`` so Jest is using a fetch api library installed only on dev. Whereas mobile devices use the fetch api provided by react-native.
This is the reason why the BackEndService requires a fetchApi parameter.

A test has been made in DahsboardScreen where the BackEndService is provided with the required parameter in the context of the mobile devices (simulator) and the log from the server attests that it is working for getting the links and flags

```
2020-03-30 01:31:37 10.0.0.4 GET /wellbeing-bienetre/api/config/links - 80 - 174.114.123.203 Expo/2.14.0.107619+CFNetwork/1125.2+Darwin/19.4.0 - 200 0 0 29
2020-03-30 01:34:56 10.0.0.4 GET /wellbeing-bienetre/api/config/flags - 80 - 174.114.123.203 Expo/2.14.0.107619+CFNetwork/1125.2+Darwin/19.4.0 - 200 0 0 37
2020-03-30 01:36:23 10.0.0.4 GET /wellbeing-bienetre/apix/config/links - 80 - 174.114.123.203 Expo/2.14.0.107619+CFNetwork/1125.2+Darwin/19.4.0 - 404 0 2 27
```

**Comment by thierryrama** [comment]
The ``BackEndService`` does not provide any method to retrieve each image file. Rather the method ``retrieveGraphLinks`` returns the urls and the jwtToken that should be used to retrieve the images. I recommend using the library ``https://github.com/itinance/react-native-fs`` by calling ``downloadFile`` and store to local file.
