### ISSUE TITLE
Duplication in on-screen help text, Q7

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#64]
On-screen help text should only say e.g. or etc, not e.g., (For example) or etc. (et cetera) 

Impacts: 
Q7 personal care, watching other videos, creating online content, crafting

**Comment by AJBouzidi** [comment]
@mullhol I looked into this, it's seems to be a EQ behavour when the screen it's resized. 
we may have to send ticket to EQ team. 
![EQ eg-1](https://user-images.githubusercontent.com/58231743/83182238-100d6880-a0f4-11ea-9677-a8d3d7ece65e.PNG)
![EQ eg-2](https://user-images.githubusercontent.com/58231743/83182240-100d6880-a0f4-11ea-939e-de713845b531.PNG)

**Comment by mullhol** [comment]
OID technical team has investigated this issue. This is a result of both the screen size of the devices being used and the inability to "hover" over the abbreviated content to see the full display since the devices are touch screen. SM will revise their questionnaire specs to include full content only, no abbreviated content.
