### ISSUE TITLE
Blue boxes on questionnaire screens 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#65]
There are blue outlines showing around the survey title on questionnaire screens. Please ensure these are not visible for production. 
![IMG_1656](https://user-images.githubusercontent.com/59370537/74449161-25fb6400-4e4a-11ea-871c-e3d3bf22bf6f.PNG)

**Comment by AJBouzidi** [comment]
@mullhol please check the EQ as we upload the new EQ specs. this is more EQ not app side.
