### ISSUE TITLE
App Flow, second entry 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#67]
When opening app for second and subsequent times : 
1) splash page should be visible for 3 seconds
2) Password page shows up second

General:
1) Statistics Canada banner is too wide, also blurry
2) Canada banner missing from bottom of page - must be included on both splash page and password page
3) App icon should be presented on password page
4) Language toggle missing on password page

**Comment by AJBouzidi** [comment]
This feature has been implemented
