### ISSUE TITLE
Information Menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#69]
1) name of menu needs to be revised to Information. Icon needs to be updated as well, as noted in homepage issue. 
2) Statistics Canada banner too wide, also blurry 
3) app logo missing from upper left hand corner
4) language toggle missing from upper right corner
5) "Return" option should be at bottom right of screen, not top left as currently presented with "back" 
6) Content should be presented on white background, not app home screen background
7) Content is missing. needs to include FAQ and Getting started information.

**Comment by AJBouzidi** [comment]
this is has been fixed
