### ISSUE TITLE
Contact Us Menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#70]
1) Name of menu needs to be revised to **Contact us**
2) Statistics Canada banner at top of screen is too large, and also blurry 
3) Menu should appear on white background, not app homepage background
4) app logo missing from top left corner
4) Language toggle missing from top right corner 
5) Content in menu is incorrect (missing email address, website address). Please update to match UX design. 
6) phone, email, and website address should be tap to open
7) "Return" option should be present at bottom right of screen, not top left as "back"

**Comment by AJBouzidi** [comment]
These features has been implemented except phone, email, and website address should be tap to open. new issue has been created for that.
