### ISSUE TITLE
App home page 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#71]
1) Statistics Canada banner should not be on home page. 
2) App icon is missing from upper left corner 
3) Settings menu too close to top/side of screen
4) Start button text should be "START YOUR SURVEY"
5) Menus at bottom should be in order from left to right: Information, Contact us, Your results
6) Menus at bottom should be in same colour as start button.  Need to match style guide from UX. 
7) Icon in Information menu needs to be updated to lowercase i 
8) Menus at bottom are currently too large - please match size from UX prototype

**Comment by AJBouzidi** [comment]
This is has been fixed and the icons from UX has been used
