### ISSUE TITLE
Entry Flow

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#72]
Entry flow when opening the app for the first time is incorrect. Flow should meet the following: 

1) tap app icon to open app
2) view splash page for 3 seconds
3) Receive request to accept notifications. Whether respondent accepts or rejects, the will flow to StatCan/wellBeingCheck#71
4) Getting started page
5) Terms and Conditions page. If respondent declines T&C, they will receive a message explaining they cannot continue without agreeing.  If they accept, they flow to StatCan/wellBeingCheck#69
6) Password set up and choosing security question/answer 
7) receive note regarding customization of notification settings
8) Land on app home page

General: 
- Statistics Canada banner should be on top of screen for splash page, getting started, terms  and conditions screens - ensure not too wide, or blurry 
- Canada banner should be on bottom of screen for splash page - ensure not too wide, or blurry. 
- App logo should be on upper left of getting started and terms and conditions pages 
- Language toggle should be on upper right of Getting Started and Terms and Conditions pages

**Comment by AJBouzidi** [comment]
this feature has been implemented
