### ISSUE TITLE
EQ: Replacement of UIWebview with WKWebView for ios8 and up

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#75]
Note

In apps that run in iOS 8 and later, use the WKWebView class instead of using UIWebView. Additionally, consider setting the WKPreferences property javaScriptEnabled to false if you render files that are not supposed to run JavaScript.
https://developer.apple.com/documentation/uikit/uiwebview

**Comment by AJBouzidi** [comment]
@Jiandong-Guo is this working fine now? I test it's working fine with iOS based on my testing.

**Comment by Jiandong-Guo** [comment]
according to the react-native document, they replaced all uiwebview with wkwebview if you add useWebKit={true}  since version 7.0.1, we have to try to deploy to apple store to see if we can pass the apple checkup, they check not only for your app code but also check all your dependency code.

**Comment by AJBouzidi** [comment]
this has been done
