### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#81]
Place Holder for FAQ: 
UX Work reference..
https://xd.adobe.com/view/ca39cd40-767f-45eb-4901-60fabecde161-bc08/screen/0a198e0d-82b7-4ea5-bce1-b82eb41d5f0f/WBC-ISR-Login-Flow-

**Comment by armonkolaei** [comment]
@AJBouzidi finished structure for FAQ and committed to master
