### ISSUE TITLE
Splash screen missing 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#88]
The splash screen is not currently in the entry flow.  When opening the app for the first time, it goes straight to the Getting Started page.

**Comment by AJBouzidi** [comment]
splash screen from 
https://xd.adobe.com/view/ca39cd40-767f-45eb-4901-60fabecde161-bc08/screen/3a41ae59-9c23-4255-a96c-f513a183d57c/WBC-Splash-Screen-Login-Flow-

![image](https://user-images.githubusercontent.com/58231743/75257438-f71eaf80-57b2-11ea-8b60-490421267a80.png)

**Comment by armonkolaei** [comment]
splash screen added with force of 3 seconds view before sending user to getting started
