### ISSUE TITLE
Return to homepage after submit 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#90]
Pressing "submit" after completing questionnaire needs to return respondent to home page.  Thank you memo to be displayed on homepage for 3 seconds.  

Currently, "submit" leaves you on the questionnaire screen. This needs to be resolved for QDRC Testing.

**Comment by AJBouzidi** [comment]
![thumbnail_Picture (Device Independent Bitmap) 1](https://user-images.githubusercontent.com/58231743/75253253-28e04800-57ac-11ea-9986-38753ed0bb72.jpg)

**Comment by AJBouzidi** [comment]
This feature has been implemented and will be in the end march release
